export const topWebShows = [
  
      {
        id: 1,
        name: "Panchayat",
        image: "https://img.etimg.com/thumb/width-1600,height-900,imgsize-1099152,resizemode-75,msid-114253305/magazines/panache/panchayat-4-release-update-when-will-jitendra-kumars-series-start-filming-check-date-plot-cast.jpg",
        description: "Abhishek Tripathi, an urban engineering graduate, navigates rural life as a panchayat secretary in Phulera, facing village politics and quirky locals. His journey tests adaptability amid humor and heart. A warm odyssey unfolds. Directed by Deepak Kumar Mishra, this 2020–2023 Amazon Prime hit, with Jitendra Kumar, Neena Gupta, and Raghubir Yadav, captures rural India’s charm with relatable comedy and emotional depth across three seasons.",
        releaseDate: "2020-04-03",
        director: "Deepak Kumar Mishra",
        genre: "Drama",
        videoId: "K1mZ3vK9xQw",
      },
    
      {
        id: 2,
        name: "Farzi",
        image: "https://res.cloudinary.com/jerrick/image/upload/v1676081578/63e6f9a900674d001c6d2521.webp",
        description: "Sunny, a disillusioned artist, crafts counterfeit money with his uncle, drawing the attention of cop Michael. Their cat-and-mouse chase tests cunning across urban shadows. A thrilling odyssey emerges. Directed by Raj & DK, this 2023 Amazon Prime series, with Shahid Kapoor and Vijay Sethupathi, blends crime and satire in a high-stakes game of deception and justice.",
        releaseDate: "2023-02-10",
        director: "Raj & DK",
        genre: "Drama",
        videoId: "L2qZ4vK9yTw",
      },
      {
        id: 5,
        name: "Twinkling Watermelon",
        image: "https://i0.wp.com/thefangirlverdict.com/wp-content/uploads/2023/10/Twinkling-Watermelon-002.jpg?resize=768%2C512&ssl=1",
        description: "Eun Gyeol, a CODA teen, time-travels to 1995, meeting his parents’ younger selves and forming a band. His journey tests family bonds across eras. A heartwarming odyssey unfolds. Directed by various, this 2023 tvN series, with Ryeoun and Choi Hyun-wook, blends music and nostalgia in a touching family tale.",
        releaseDate: "2023-09-25",
        director: "[Various]",
        genre: "Drama",
        videoId: "U5mZ3vK9xQw",
      },
      {
        id: 62,
        name: "Alice in Borderland Season 2",
        image: "https://dnm.nflximg.net/api/v6/BvVbc2Wxr2w6QuoANoSpJKEIWjQ/AAAAQUGRKsxWXRyUn1txrhF-yqcNsyJFTiMsDMCZ4I6_bagQmYvtYefWJKshETnSPu3XRZKYsygEY9WDA6pu1g9WzfaiuCGkvQqigLz6zcAAYqvZgrVKHtAYxp_-RYFB24gMCYwVG7MX_R7YtPWI74WSDnLoqzw.jpg?r=b2d",
        description: "Arisu and Usagi return to a desolate Tokyo, facing deadlier face-card games run by enigmatic citizens like the King of Spades, who unleashes chaos with relentless attacks. Their quest to collect all cards tests survival and strategy against escalating threats. A tense odyssey unfolds. Directed by Shinsuke Sato, this 2022 Netflix hit, with Kento Yamazaki and Tao Tsuchiya, deepens the manga adaptation with stunning visuals and emotional stakes, culminating in a shocking Joker card twist that hints at more mysteries.",
        releaseDate: "2022-12-22",
        director: "Shinsuke Sato",
        genre: "Drama",
        videoId: "P2mZ3vK9xQw",
      },
      {
        id: 1,
        name: "Queen of Tears",
        image: "https://resizing.flixster.com/f5D1_g0d3nwVN3N1H4kL_A_RzHE=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p26780072_b_h10_af.jpg",
        description: "Hong Hae-in and Baek Hyun-woo’s marriage crumbles under corporate intrigue, only to reignite with a life-threatening diagnosis. Their quest for love tests resilience amid wealth’s chaos. A tearful odyssey emerges. Directed by Jang Young-woo and Kim Hee-won, this 2024 tvN hit, with Kim Soo-hyun and Kim Ji-won, blends romance and drama in a billionaire’s world.",
        releaseDate: "2024-03-09",
        director: "Jang Young-woo, Kim Hee-won",
        genre: "Drama",
        videoId: "T4qZ5vJ8r3Y",
      },
      {
        id: 3,
        name: "Mirzapur",
        image: "https://variety.com/wp-content/uploads/2024/06/Mirzapur-3-poster.jpg?w=1000&h=563&crop=1",
        description: "Akhandanand Tripathi, the crime lord Kaleen Bhaiya, rules Mirzapur with an iron fist, sparking rivalries with Guddu and Munna. Their power struggle tests loyalty amid bloodshed. A gritty odyssey unfolds. Directed by Karan Anshuman and Gurmmeet Singh, this 2018–2024 Amazon Prime epic, with Pankaj Tripathi and Ali Fazal, delivers intense action and drama across three seasons.",
        releaseDate: "2018-11-16",
        director: "Karan Anshuman, Gurmmeet Singh",
        genre: "Drama",
        videoId: "M3mZ3vK9xQw",
      },
      {
        id: 3,
        name: "Moving",
        image: "https://images.herzindagi.info/image/2023/Aug/moving-all-you-need-to-know.jpg",
        description: "Superpowered teens and their parents hide from a shadowy organization hunting them, forced into action across Seoul. Their journey tests strength and secrecy in a perilous odyssey. A gripping saga unfolds. Directed by Park In-je, this 2023 Disney+ hit, with Lee Jung-ha and Han Hyo-joo, adapts Kang Full’s webtoon with action and emotional depth.",
        releaseDate: "2023-08-09",
        director: "Park In-je",
        genre: "Drama",
        videoId: "S3mZ3vK9xQw",
      },
      {
        id: 4,
        name: "Gullak",
        image: "https://jiotvimages.cdn.jio.com/imagespublic/93/72/7a69f1931e80573b87bde3b465fbec8b_1696438579875_l_medium.jpg",
        description: "The Mishra family navigates middle-class life in a small town, facing daily joys and quarrels through the eyes of their piggy bank. Their journey tests love and resilience. A heartwarming odyssey emerges. Directed by Palash Vaswani, this 2019–2024 SonyLIV series, with Jameel Khan and Geetanjali Kulkarni, weaves gentle humor and family bonds across four seasons.",
        releaseDate: "2019-06-27",
        director: "Palash Vaswani",
        genre: "Drama",
        videoId: "N4qZ5vJ8r3Y",
      },
    {
      id: 3,
      name: "The Last of Us Season 2",
      image: "https://images-cdn3.welcomesoftware.com/assets/The+Last+Of+Us-S2_HO_KA_16x9_v03.jpg/Zz1jMzFkMGFkMjA5YWIxMWYwOWM0ZDNlYTAyMDczN2Q3YQ==?width=1200",
      description: "Joel and Ellie confront a treacherous world five years after Season 1, facing new threats and internal conflicts with Abby’s arrival. Their trek tests survival and forgiveness amid post-apocalyptic ruins. A harrowing saga emerges. Directed by various, this 2025 Max series, with Pedro Pascal and Bella Ramsey, adapts the game with intense action and emotional resonance in a bleak, unpredictable landscape.",
      releaseDate: "2025-04-01",
      director: "[Various]",
      genre: "Drama",
      videoId: "S3mZ3vK9xQw",
    },
    {
      id: 4,
      name: "Black Mirror Season 7",
      image: "https://img.etimg.com/thumb/width-1600,height-900,imgsize-62734,resizemode-75,msid-113533868/news/international/us/black-mirror-season-7-expected-release-date-new-cast-and-plot-details-revealed.jpg",
      description: "Charlie Brooker’s anthology returns with six episodes, including a *USS Callister* sequel, exploring tech’s dark grip on humanity. Each story tests morality across near-future dystopias. A mind-bending journey unfolds. Directed by various, this 2025 Netflix hit, with Cristin Milioti and Awkwafina, blends humor and horror in a chilling sci-fi narrative.",
      releaseDate: "2025-04-10",
      director: "[Various]",
      genre: "Drama",
      videoId: "T4qZ5vJ8r3Y",
    },
    {
      id: 5,
      name: "Daredevil: Born Again",
      image: "https://bgr.com/wp-content/uploads/2024/04/Daredevil-Born-Again.jpg?quality=82&strip=all",
      description: "Matt Murdock fights for justice as a blind lawyer, clashing with ex-mob boss Wilson Fisk, now New York’s mayor. Their duel through law and violence tests ethics and power. A gritty odyssey emerges. Directed by various, this 2025 Disney+ series, with Charlie Cox and Vincent D’Onofrio, revives the Marvel hero with intense action and moral complexity.",
      releaseDate: "2025-03-01",
      director: "[Various]",
      genre: "Drama",
      videoId: "U5mZ3vK9xQw",
    },
    {
        id: 6,
        name: "Kingdom",
        image: "https://resizing.flixster.com/RsyHYSwRDvWjwmEkCdaiw8Fi7uM=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p16296544_i_h9_ac.jpg",
        description: "Prince Lee Chang battles a zombie plague threatening Joseon, racing through haunted lands with his guard. Their quest tests royalty and survival. A dark odyssey emerges. Directed by various, this 2019–2020 Netflix hit, with Ju Ji-hoon, redefines historical horror with political intrigue.",
        releaseDate: "2019-01-25",
        director: "[Various]",
        genre: "Drama",
        videoId: "V6qZ4vK9yTw",
      },
      {
        id: 7,
        name: "Sweet Home Season 3",
        image: "https://dnm.nflximg.net/api/v6/2DuQlx0fM4wd1nzqm5BFBi6ILa8/AAAAQckHw5fvGLIg442sqWsGzMwhmXui0E8vjjhaFiJz0oSEFzQ4RAieVwVPvI7jUhK8UKC6bNkPeHKp3J2LpC-Kr5ox0yalWe977s2vS0itd2vAokv1Jh3FscL-Izc1l5-eXhpdjCytYdB0BHRzdw.jpg?r=f0b",
        description: "Survivors Cha Hyun-su and others fight monstrous transformations in a collapsing world, seeking a cure amid chaos. Their journey tests humanity in a brutal odyssey. A tense saga unfolds. Directed by various, this 2025 Netflix sequel, with Song Kang, escalates the survival horror from the webtoon.",
        releaseDate: "2025-07-15",
        director: "[Various]",
        genre: "Drama",
        videoId: "W7mZ3vK9xQw",
      },
    {
      id: 7,
      name: "The Handmaid’s Tale Season 6",
      image: "https://cdn.mos.cms.futurecdn.net/x48W3YdVY96egq2WXRuSDc.jpg",
      description: "June Osborne leads a final rebellion against Gilead’s tyranny, facing brutal oppression and personal loss. Her quest for freedom tests resilience in a dystopian nightmare. A defiant odyssey emerges. Directed by various, this 2025 Hulu finale, with Elisabeth Moss, adapts Margaret Atwood’s novel with raw emotion and intense drama.",
      releaseDate: "2025-04-08",
      director: "[Various]",
      genre: "Drama",
      videoId: "W7mZ3vK9xQw",
    },
    {
        id: 8,
        name: "Vagabond",
        image: "https://www.wheninmanila.com/wp-content/uploads/2019/11/12ReasonsWhyYouShouldWatchVagabond-e1574651527106.jpeg",
        description: "Cha Dal-gun uncovers a conspiracy after a plane crash, joining a NIS agent in a global chase. Their quest tests justice amid danger. A thrilling odyssey emerges. Directed by Yoo In-sik, this 2019 Netflix series, with Lee Seung-gi, blends action and intrigue.",
        releaseDate: "2019-09-20",
        director: "Yoo In-sik",
        genre: "Drama",
        videoId: "X8qZ5vJ8r3Y",
      },
      {
        id: 19,
        name: "Happiness",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ5GI6yOndpvnyGJrrrUmK7Nu9VxwJxtl4RQ&s",
        description: "Apartment residents face a virus turning them into monsters, led by a detective and soldier. Their fight tests survival in a confined odyssey. A tense saga unfolds. Directed by Ahn Gil-ho, this 2021 tvN series, with Han Hyo-joo, offers zombie thriller drama.",
        releaseDate: "2021-11-05",
        director: "Ahn Gil-ho",
        genre: "Drama",
        videoId: "I9mZ3vK9xQw",
      },
      {
        id: 14,
        name: "18 Again",
        image: "https://m.media-amazon.com/images/S/pv-target-images/1db8d93a9cef9b0aebeba8f7f5390b56489adc970b37db13a32e8afef13df004.jpg",
        description: "Hong Dae-young, aging and divorced, transforms into his 18-year-old self, reconnecting with his family. His journey tests second chances in a heartfelt odyssey. A family saga emerges. Directed by Ha Byeong-hoon, this 2020 JTBC series, with Lee Do-hyun, adapts *17 Again* with warmth.",
        releaseDate: "2020-09-21",
        director: "Ha Byeong-hoon",
        genre: "Drama",
        videoId: "D4qZ4vK9yTw",
      },
      {
        id: 1,
        name: "Wednesday Season 1",
        image: "https://m.media-amazon.com/images/I/71SenBrUHEL._AC_UF894,1000_QL80_.jpg",
        description: "Wednesday Addams, sent to Nevermore Academy, uncovers a supernatural murder mystery tied to her psychic visions, aided by her roommate Enid and new ally Tyler. Her journey through gothic halls tests wit and resilience against a monstrous threat. A quirky odyssey unfolds. Directed by Tim Burton and others, this 2022 Netflix hit, with Jenna Ortega, blends dark humor and suspense, adapting the Addams Family with a fresh, eerie charm and a cliffhanger finale in a world of outcasts.",
        releaseDate: "2022-11-23",
        director: "Tim Burton, [Various]",
        genre: "Drama",
        videoId: "O1mZ3vK9xQw",
      },
    {
      id: 9,
      name: "Alien: Earth",
      image: "https://www.ecranlarge.com/content/uploads/2024/11/alien-earth-date-de-sortie-affiche.jpg",
      description: "Soldiers uncover a crashed alien ship on Earth, facing the first Xenomorph two years before *Alien*. Their mission tests bravery against cosmic terror. A chilling odyssey emerges. Created by Noah Hawley, this 2025 FX/Hulu series, with Sydney Chandler, redefines the franchise with suspense and corporate intrigue in a bleak future.",
      releaseDate: "2025-06-20",
      director: "[Various]",
      genre: "Drama",
      videoId: "Y9mZ3vK9xQw",
    },
    {
      id: 10,
      name: "Andor Season 2",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOEJHa0u0XtzCJE9EUwyaLTMVL868i6bfFeA&s",
      description: "Cassian Andor deepens his rebellion over four years leading to *Rogue One*, facing espionage and Imperial forces. His journey tests sacrifice in a gritty galaxy. A rebel saga emerges. Directed by various, this 2025 Disney+ series, with Diego Luna, delivers a tense *Star Wars* thriller with rich world-building.",
      releaseDate: "2025-04-22",
      director: "[Various]",
      genre: "Drama",
      videoId: "Z0qZ4vK9yTw",
    },

    {
      id: 12,
      name: "Succession Season 4",
      image: "https://helios-i.mashable.com/imagery/articles/01Z2sfofhqPr4nJWrir9QOd/hero-image.fill.size_1248x702.v1680816955.jpg",
      description: "The Roy family battles for control after Logan’s death, navigating power struggles and corporate chaos. Their journey tests loyalty amid wealth’s absurdity. A sharp saga emerges. Directed by various, this 2023 HBO Max finale, with Brian Cox and Jeremy Strong, delivers incisive satire and emotional depth.",
      releaseDate: "2023-03-26",
      director: "[Various]",
      genre: "Drama",
      videoId: "B2qZ5vJ8r3Y",
    },
    {
      id: 13,
      name: "Breaking Bad",
      image: "https://rukminim2.flixcart.com/image/850/1000/jbgtnrk0/poster/f/8/u/medium-ashd-wall-poster-breaking-bad-jesse-pinkman-aaron-paul-original-imaehbd6cb9yj6uf.jpeg?q=90&crop=false",
      description: "Walter White, a chemistry teacher turned meth kingpin, builds an empire with Jesse Pinkman to secure his family’s future. His descent tests morality in a criminal odyssey. A gripping saga emerges. Created by Vince Gilligan, this 2008–2013 AMC classic, with Bryan Cranston, remains a benchmark of drama and tension.",
      releaseDate: "2008-01-20",
      director: "[Various]",
      genre: "Drama",
      videoId: "C3mZ3vK9xQw",
    },
    {
      id: 14,
      name: "Game of Thrones",
      image: "https://i0.wp.com/www.buzztt.com/site/wp-content/uploads/2016/08/GoT.jpg?fit=1920%2C1200&ssl=1",
      description: "Nine noble families vie for Westeros’ throne as an ancient enemy awakens, weaving a tale of power and betrayal. Their journey tests honor across epic battles. A legendary odyssey unfolds. Created by David Benioff and D.B. Weiss, this 2011–2019 HBO Max epic, with Emilia Clarke, redefined fantasy drama.",
      releaseDate: "2011-04-17",
      director: "[Various]",
      genre: "Drama",
      videoId: "D4qZ4vK9yTw",
    },
    {
      id: 15,
      name: "Stranger Things",
      image: "https://m.media-amazon.com/images/I/91txlu5NEfL.jpg",
      description: "A group of kids in 1980s Hawkins battles supernatural forces and government secrets after Eleven’s arrival. Their journey tests friendship in a monster-filled world. A nostalgic saga emerges. Created by the Duffer Brothers, this 2016–2025 Netflix hit, with Millie Bobby Brown, blends ’80s vibes and suspense.",
      releaseDate: "2016-07-15",
      director: "[Various]",
      genre: "Drama",
      videoId: "E5mZ3vK9xQw",
    },

  
  ];