export const actionMovies = [
    {
      id: 1,
      name: "RRR",
      image: "https://i.ytimg.com/vi/f_vbAtFSEc0/maxresdefault.jpg",
      description: "A historical fiction action drama about the Indian freedom struggle.",
      releaseDate: "2022-03-25",
      director: "S.S. Rajamouli",
      genre: "Action",
      videoId: "f_vbAtFSEc0",
    },
    {
      id: 2,
      name: "Baahubali 2",
      image: "https://i.ytimg.com/vi/G62HrubdD6o/maxresdefault.jpg",
      description: "Epic battle story in Mahishmati kingdom.",
      releaseDate: "2017-04-28",
      director: "S.S. Rajamouli",
      genre: "Action",
      videoId: "G62HrubdD6o",
    },
    {
      id: 3,
      name: "Aquaman",
      image: "https://rukminim2.flixcart.com/image/850/1000/l0bbonk0/poster/4/1/i/small-aquaman-poster-sticker-self-adhesive-poster-12-inch-x-18-original-imagc4sgsggqpftq.jpeg?q=90&crop=false",
      description: "Arthur Curry, a half-human, half-Atlantean, discovers his destiny as heir to the underwater kingdom of Atlantis. When his half-brother Orm declares war on the surface world, Arthur must claim the throne to prevent global catastrophe. Guided by Mera and trained by Vulko, he wields the trident of Atlan, battling ocean beasts and rival factions. Director James Wan delivers a vibrant, action-packed spectacle, blending mythic lore with dazzling underwater visuals. Jason Momoa’s charismatic performance anchors this DC epic, redefining the superhero genre with swashbuckling energy and environmental stakes.",
      releaseDate: "2018-12-21",
      director: "James Wan",
      genre: "Action",
      videoId: "W7qZ5vK9m4Z",
    },
    {
      id: 4,
      name: "John Wick",
      image: "https://rukminim3.flixcart.com/image/850/1000/xif0q/poster/8/z/a/medium-movie-john-wick-on-fine-art-paper-hd-quality-wallpaper-original-imah3bzdr9fnnyny.jpeg?q=20&crop=false",
      description: "A retired hitman seeks vengeance for a personal loss.",
      releaseDate: "2014-10-24",
      director: "Chad Stahelski",
      genre: "Action",
      videoId: "2AUmvWm5ZDQ",
    },
    {
      id: 27,
      name: "Kalki 2898 AD",
      image: "https://i3.ytimg.com/vi/y1-w1kUGuz8/maxresdefault.jpg",
      description: "In the dystopian year 2898 AD, the city of Kasi languishes under the tyrannical rule of Supreme Yaskin, while humanity’s hope fades. An immortal warrior, Ashwatthama, guards SUM-80, a woman carrying the unborn child believed to be Kalki, Lord Vishnu’s final avatar. Joined by Bhairava, a rogue bounty hunter, they battle Yaskin’s forces to protect the prophecy. Blending Hindu mythology with sci-fi grandeur, director Nag Ashwin crafts a visually stunning epic, weaving Mahabharata references into a futuristic saga. This ambitious film, starring Prabhas and Amitabh Bachchan, sets the stage for a cinematic universe.",
      releaseDate: "2024-06-27",
      director: "Nag Ashwin",
      genre: "Action",
      videoId: "X9qZ5vJ8r3Y",
    },
    {
      id: 6,
      name: "The Dark Knight",
      image: "https://image.tmdb.org/t/p/original/dJD4i4xYkUP5ELuGGzc4B6Fermn.jpg",
      description: "Batman faces a chaotic criminal mastermind in Gotham.",
      releaseDate: "2008-07-18",
      director: "Christopher Nolan",
      genre: "Action",
      videoId: "EXeTwQWrcwY",
    },
    {
      id: 7,
      name: "KGF: Chapter 2",
      image: "https://images.indianexpress.com/2022/05/KGF2-1200by667.jpg?w=414",
      description: "A gangster rises to power in a brutal gold mining empire.",
      releaseDate: "2022-04-14",
      director: "Prashanth Neel",
      genre: "Action",
      videoId: "JHvl5S2iSNQ",
    },
    {
      id: 8,
      name: "Terminator 2: Judgment Day",
      image: "https://m.media-amazon.com/images/S/pv-target-images/913c5996fc687a783b6b082c7ae463052815ee7841a4b2c0ea9aa95e948d8563.jpg",
      description: "A cyborg is sent to protect a boy from a deadly machine.",
      releaseDate: "1991-07-03",
      director: "James Cameron",
      genre: "Action",
      videoId: "CRRlbK5w8AE",
    },
    {
      id: 9,
      name: "Salaar: Part 1 – Ceasefire",
      image: "https://igimage.indiaglitz.com/tamil/gallery/movies/salaar2023/main.jpg",
      description: "In the fictional realm of Khansaar, a blood-soaked power struggle unfolds as Deva, a fierce warrior, returns to protect his childhood friend Vardha, the heir to a warring empire. Facing betrayal, rival tribes, and a mysterious past, Deva unleashes relentless combat to secure Vardha’s throne. Director Prashanth Neel crafts a gritty, high-octane saga, echoing his *KGF* legacy with intricate world-building and explosive action. Prabhas delivers a commanding performance, blending stoic intensity with raw emotion, in this cliffhanger epic that sets up a grand sequel.",
      releaseDate: "2023-12-22",
      director: "Prashanth Neel",
      genre: "Action",
      videoId: "Y8mL3v9z7Rw",
    },
    {
      id: 10,
      name: "Mission: Impossible – Fallout",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00040397-kevtlhgntv-landscape.jpg",
      description: "A spy races to stop a global catastrophe.",
      releaseDate: "2018-07-27",
      director: "Christopher McQuarrie",
      genre: "Action",
      videoId: "wb49-oV0F78",
    },
    {
      id: 11,
      name: "Gladiator",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsrI_vM0OYfn5eNnnBSgBUzptztMagZIbh0A&s",
      description: "A betrayed general seeks revenge in the Roman arena.",
      releaseDate: "2000-05-05",
      director: "Ridley Scott",
      genre: "Action",
      videoId: "FI1ylg4GKv8",
    },
    {
      id: 12,
      name: "The Raid: Redemption",
      image: "https://m.media-amazon.com/images/I/81-OtJYlfZL._UF1000,1000_QL80_.jpg",
      description: "A SWAT team fights through a crime lord’s stronghold.",
      releaseDate: "2012-03-23",
      director: "Gareth Evans",
      genre: "Action",
      videoId: "m6Q7KnG6dvk",
    },
    {
      id: 13,
      name: "Avengers: Endgame",
      image: "https://cdn.marvel.com/content/1x/avengersendgame_lob_mas_mob_01.jpg",
      description: "Heroes unite to reverse a cosmic catastrophe.",
      releaseDate: "2019-04-26",
      director: "Anthony Russo, Joe Russo",
      genre: "Action",
      videoId: "TcMBFSGVi1c",
    },
    {
      id: 14,
      name: "Thor: Ragnarok",
      image: "https://m.media-amazon.com/images/I/A1mtrMhDuFL._AC_UF1000,1000_QL80_.jpg",
      description: "Thor, the Norse god of thunder, finds himself imprisoned on the chaotic planet Sakaar after being banished from Asgard. Facing the destruction of his home by the ruthless goddess Hela, he teams up with Loki, Hulk, and Valkyrie in a desperate bid to escape, overthrow Hela, and prevent Ragnarok—the prophesied annihilation of Asgard. Packed with vibrant battles, cosmic humor, and a quest for redemption, this adventure redefines Thor’s legacy in the Marvel universe.",
      releaseDate: "2017-11-03",
      director: "Taika Waititi",
      genre: "Action",
      videoId: "ue80QwXMRHg",
    },
    {
      id: 15,
      name: "The Witch: Part 1 – The Subversion",
      image: "https://windowsonworlds.com/wp-content/uploads/2019/04/the-witch-banner.jpg?w=1440",
      description: "Ja-yoon, a teenage girl raised by adoptive parents in rural South Korea, lives quietly until her past unravels after appearing on a TV talent show. Hunted by shadowy operatives linked to her childhood, she discovers unnatural abilities tied to a secret experiment. As assassins close in, Ja-yoon unleashes her powers in brutal, high-octane clashes, seeking answers about her origins. Director Park Hoon-jung blends gritty action with chilling mystery, crafting a thrilling tale of identity and rebellion. Kim Da-mi’s breakout performance anchors this Korean blockbuster, setting up an explosive sequel.",
      releaseDate: "2018-06-27",
      director: "Park Hoon-jung",
      genre: "Action",
      videoId: "K5mZ3v9yQw",
    },
    {
      id: 16,
      name: "Top Gun: Maverick",
      image: "https://i.redd.it/top-gun-1986-poster-or-top-gun-maverick-2022-poster-v0-xdtjf63btwec1.jpg?width=1920&format=pjpg&auto=webp&s=8ac99e8e44b04b2d84a8e7b9d128d09ca8a42347",
      description: "A pilot trains recruits for a dangerous mission.",
      releaseDate: "2022-05-27",
      director: "Joseph Kosinski",
      genre: "Action",
      videoId: "giXco2jaZ_4",
    },
    {
      id: 17,
      name: "Train to Busan Presents: Peninsula",
      image: "https://i.ytimg.com/vi/yVucSRLLeIM/hqdefault.jpg",
      description: "Four years after a zombie outbreak ravaged South Korea, ex-soldier Jung-seok joins a rogue team to infiltrate the infested peninsula and retrieve a truckload of cash. Landing in a desolate Incheon, they face hordes of ravenous undead and a rogue militia led by a deranged commander. Teaming with survivors Min-jung and her daughters, Jung-seok battles for redemption in high-octane chases and explosive showdowns. Director Yeon Sang-ho expands the *Train to Busan* universe with relentless action and gritty survival stakes. Gang Dong-won’s stoic lead drives this thrilling, post-apocalyptic ride.",
      releaseDate: "2020-07-15",
      director: "Yeon Sang-ho",
      genre: "Action",
      videoId: "P8nZ3vK7xRt",
    },
    {
      id: 18,
      name: "Marco",
      image: "https://i.ytimg.com/vi/AdwGOloQcAs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDEtfoXZcXEm5Ahov3MmYvvD_5tdQ",
      description: "Marco Jr., a ruthless gangster raised in the violent underworld of Kochi, inherits his father Victor’s criminal empire after a brutal betrayal. Driven by vengeance, he wages a bloody war against rival syndicates and corrupt cops, carving a path of destruction with his unmatched combat skills. As loyalties fracture and secrets unravel, Marco’s quest for power tests his humanity in a city soaked in chaos. Director Haneef Adeni delivers a raw, adrenaline-fueled spectacle, with Unni Mukundan’s ferocious lead performance anchoring this Malayalam action epic, pushing regional cinema’s boundaries into gritty, global territory.",
      releaseDate: "2021-12-20",
      director: "Haneef Adeni",
      genre: "Action",
      videoId: "M7qZ4vK9yTw",
    },
    {
      id: 34,
      name: "Venom: The Last Dance",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1sHa9CO9Tj_CfCSsN0UrUYk6ApcGngkDmRA&s",
      description: "Eddie Brock and his alien symbiote Venom are fugitives, hunted by a secretive government force after their chaotic past. As a monstrous invasion from Venom’s homeworld threatens Earth, the duo faces relentless mercenaries and a primal symbiote god, Knull’s wrath. Teaming with unlikely allies, Eddie battles for survival in explosive chases and visceral clashes, confronting their bond’s limits. Director Kelly Marcel closes the trilogy with a wild, emotional ride, blending dark humor and savage action. Tom Hardy’s raw dual performance anchors this comic-book epic, redefining Eddie and Venom’s legacy.",
      releaseDate: "2024-10-25",
      director: "Kelly Marcel",
      genre: "Action",
      videoId: "V8mZ3vK9xQw",
    },
    {
      id: 20,
      name: "Extraction",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY14x4RIxfG6RdW6luPDetHDJMNxgWAJQ5Qg&s",
      description: "A mercenary rescues a kidnapped child in a volatile city.",
      releaseDate: "2020-04-24",
      director: "Sam Hargrave",
      genre: "Action",
      videoId: "L6P3nI6VnlY",
    },
   
  ];

  