export const actionMovies = [
    {
        id: 4,
        name: "John Wick",
        image: "https://rukminim3.flixcart.com/image/850/1000/xif0q/poster/8/z/a/medium-movie-john-wick-on-fine-art-paper-hd-quality-wallpaper-original-imah3bzdr9fnnyny.jpeg?q=20&crop=false",
        description: "A retired hitman seeks vengeance for a personal loss.",
        releaseDate: "2014-10-24",
        director: "Chad Stahelski",
        genre: "Action",
        videoId: "2AUmvWm5ZDQ",
      },
      {
        id: 27,
        name: "Kalki 2898 AD",
        image: "https://i3.ytimg.com/vi/y1-w1kUGuz8/maxresdefault.jpg",
        description: "In the dystopian year 2898 AD, the city of Kasi languishes under the tyrannical rule of Supreme Yaskin, while humanity’s hope fades. An immortal warrior, Ashwatthama, guards SUM-80, a woman carrying the unborn child believed to be Kalki, Lord Vishnu’s final avatar. Joined by Bhairava, a rogue bounty hunter, they battle Yaskin’s forces to protect the prophecy. Blending Hindu mythology with sci-fi grandeur, director Nag Ashwin crafts a visually stunning epic, weaving Mahabharata references into a futuristic saga. This ambitious film, starring Prabhas and Amitabh Bachchan, sets the stage for a cinematic universe.",
        releaseDate: "2024-06-27",
        director: "Nag Ashwin",
        genre: "Action",
        videoId: "X9qZ5vJ8r3Y",
      },
      {
        id: 6,
        name: "The Dark Knight",
        image: "https://image.tmdb.org/t/p/original/dJD4i4xYkUP5ELuGGzc4B6Fermn.jpg",
        description: "Batman faces a chaotic criminal mastermind in Gotham.",
        releaseDate: "2008-07-18",
        director: "Christopher Nolan",
        genre: "Action",
        videoId: "EXeTwQWrcwY",
      },
    {
      id: 1,
      name: "RRR",
      image: "https://i.ytimg.com/vi/f_vbAtFSEc0/maxresdefault.jpg",
      description: "A historical fiction action drama about the Indian freedom struggle.",
      releaseDate: "2022-03-25",
      director: "S.S. Rajamouli",
      genre: "Action",
      videoId: "f_vbAtFSEc0",
    },
    {
      id: 2,
      name: "Baahubali 2",
      image: "https://i.ytimg.com/vi/G62HrubdD6o/maxresdefault.jpg",
      description: "Epic battle story in Mahishmati kingdom.",
      releaseDate: "2017-04-28",
      director: "S.S. Rajamouli",
      genre: "Action",
      videoId: "G62HrubdD6o",
    },
    {
      id: 3,
      name: "Aquaman",
      image: "https://rukminim2.flixcart.com/image/850/1000/l0bbonk0/poster/4/1/i/small-aquaman-poster-sticker-self-adhesive-poster-12-inch-x-18-original-imagc4sgsggqpftq.jpeg?q=90&crop=false",
      description: "Arthur Curry, a half-human, half-Atlantean, discovers his destiny as heir to the underwater kingdom of Atlantis. When his half-brother Orm declares war on the surface world, Arthur must claim the throne to prevent global catastrophe. Guided by Mera and trained by Vulko, he wields the trident of Atlan, battling ocean beasts and rival factions. Director James Wan delivers a vibrant, action-packed spectacle, blending mythic lore with dazzling underwater visuals. Jason Momoa’s charismatic performance anchors this DC epic, redefining the superhero genre with swashbuckling energy and environmental stakes.",
      releaseDate: "2018-12-21",
      director: "James Wan",
      genre: "Action",
      videoId: "W7qZ5vK9m4Z",
    },
    {
        id: 1,
        name: "RRR",
        image: "https://i.ytimg.com/vi/f_vbAtFSEc0/maxresdefault.jpg",
        description: "A historical fiction action drama about the Indian freedom struggle.",
        releaseDate: "2022-03-25",
        director: "S.S. Rajamouli",
        genre: "Action",
        videoId: "f_vbAtFSEc0",
      },
      {
        id: 2,
        name: "Baahubali 2",
        image: "https://i.ytimg.com/vi/G62HrubdD6o/maxresdefault.jpg",
        description: "Epic battle story in Mahishmati kingdom.",
        releaseDate: "2017-04-28",
        director: "S.S. Rajamouli",
        genre: "Action",
        videoId: "G62HrubdD6o",
      },
      {
        id: 3,
        name: "Aquaman",
        image: "https://rukminim2.flixcart.com/image/850/1000/l0bbonk0/poster/4/1/i/small-aquaman-poster-sticker-self-adhesive-poster-12-inch-x-18-original-imagc4sgsggqpftq.jpeg?q=90&crop=false",
        description: "Arthur Curry, a half-human, half-Atlantean, discovers his destiny as heir to the underwater kingdom of Atlantis. When his half-brother Orm declares war on the surface world, Arthur must claim the throne to prevent global catastrophe. Guided by Mera and trained by Vulko, he wields the trident of Atlan, battling ocean beasts and rival factions. Director James Wan delivers a vibrant, action-packed spectacle, blending mythic lore with dazzling underwater visuals. Jason Momoa’s charismatic performance anchors this DC epic, redefining the superhero genre with swashbuckling energy and environmental stakes.",
        releaseDate: "2018-12-21",
        director: "James Wan",
        genre: "Action",
        videoId: "W7qZ5vK9m4Z",
      },
    {
      id: 7,
      name: "KGF: Chapter 2",
      image: "https://images.indianexpress.com/2022/05/KGF2-1200by667.jpg?w=414",
      description: "A gangster rises to power in a brutal gold mining empire.",
      releaseDate: "2022-04-14",
      director: "Prashanth Neel",
      genre: "Action",
      videoId: "JHvl5S2iSNQ",
    },
    {
      id: 8,
      name: "Terminator 2: Judgment Day",
      image: "https://m.media-amazon.com/images/S/pv-target-images/913c5996fc687a783b6b082c7ae463052815ee7841a4b2c0ea9aa95e948d8563.jpg",
      description: "A cyborg is sent to protect a boy from a deadly machine.",
      releaseDate: "1991-07-03",
      director: "James Cameron",
      genre: "Action",
      videoId: "CRRlbK5w8AE",
    },
    {
      id: 9,
      name: "Salaar: Part 1 – Ceasefire",
      image: "https://igimage.indiaglitz.com/tamil/gallery/movies/salaar2023/main.jpg",
      description: "In the fictional realm of Khansaar, a blood-soaked power struggle unfolds as Deva, a fierce warrior, returns to protect his childhood friend Vardha, the heir to a warring empire. Facing betrayal, rival tribes, and a mysterious past, Deva unleashes relentless combat to secure Vardha’s throne. Director Prashanth Neel crafts a gritty, high-octane saga, echoing his *KGF* legacy with intricate world-building and explosive action. Prabhas delivers a commanding performance, blending stoic intensity with raw emotion, in this cliffhanger epic that sets up a grand sequel.",
      releaseDate: "2023-12-22",
      director: "Prashanth Neel",
      genre: "Action",
      videoId: "Y8mL3v9z7Rw",
    },
    {
      id: 10,
      name: "Mission: Impossible – Fallout",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00040397-kevtlhgntv-landscape.jpg",
      description: "A spy races to stop a global catastrophe.",
      releaseDate: "2018-07-27",
      director: "Christopher McQuarrie",
      genre: "Action",
      videoId: "wb49-oV0F78",
    },
    {
      id: 11,
      name: "Gladiator",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsrI_vM0OYfn5eNnnBSgBUzptztMagZIbh0A&s",
      description: "A betrayed general seeks revenge in the Roman arena.",
      releaseDate: "2000-05-05",
      director: "Ridley Scott",
      genre: "Action",
      videoId: "FI1ylg4GKv8",
    },
    {
      id: 12,
      name: "The Raid: Redemption",
      image: "https://m.media-amazon.com/images/I/81-OtJYlfZL._UF1000,1000_QL80_.jpg",
      description: "A SWAT team fights through a crime lord’s stronghold.",
      releaseDate: "2012-03-23",
      director: "Gareth Evans",
      genre: "Action",
      videoId: "m6Q7KnG6dvk",
    },
    {
      id: 13,
      name: "Avengers: Endgame",
      image: "https://cdn.marvel.com/content/1x/avengersendgame_lob_mas_mob_01.jpg",
      description: "Heroes unite to reverse a cosmic catastrophe.",
      releaseDate: "2019-04-26",
      director: "Anthony Russo, Joe Russo",
      genre: "Action",
      videoId: "TcMBFSGVi1c",
    },
    {
      id: 14,
      name: "Thor: Ragnarok",
      image: "https://m.media-amazon.com/images/I/A1mtrMhDuFL._AC_UF1000,1000_QL80_.jpg",
      description: "Thor, the Norse god of thunder, finds himself imprisoned on the chaotic planet Sakaar after being banished from Asgard. Facing the destruction of his home by the ruthless goddess Hela, he teams up with Loki, Hulk, and Valkyrie in a desperate bid to escape, overthrow Hela, and prevent Ragnarok—the prophesied annihilation of Asgard. Packed with vibrant battles, cosmic humor, and a quest for redemption, this adventure redefines Thor’s legacy in the Marvel universe.",
      releaseDate: "2017-11-03",
      director: "Taika Waititi",
      genre: "Action",
      videoId: "ue80QwXMRHg",
    },
    {
      id: 15,
      name: "The Witch: Part 1 – The Subversion",
      image: "https://windowsonworlds.com/wp-content/uploads/2019/04/the-witch-banner.jpg?w=1440",
      description: "Ja-yoon, a teenage girl raised by adoptive parents in rural South Korea, lives quietly until her past unravels after appearing on a TV talent show. Hunted by shadowy operatives linked to her childhood, she discovers unnatural abilities tied to a secret experiment. As assassins close in, Ja-yoon unleashes her powers in brutal, high-octane clashes, seeking answers about her origins. Director Park Hoon-jung blends gritty action with chilling mystery, crafting a thrilling tale of identity and rebellion. Kim Da-mi’s breakout performance anchors this Korean blockbuster, setting up an explosive sequel.",
      releaseDate: "2018-06-27",
      director: "Park Hoon-jung",
      genre: "Action",
      videoId: "K5mZ3v9yQw",
    },
    {
      id: 16,
      name: "Top Gun: Maverick",
      image: "https://i.redd.it/top-gun-1986-poster-or-top-gun-maverick-2022-poster-v0-xdtjf63btwec1.jpg?width=1920&format=pjpg&auto=webp&s=8ac99e8e44b04b2d84a8e7b9d128d09ca8a42347",
      description: "A pilot trains recruits for a dangerous mission.",
      releaseDate: "2022-05-27",
      director: "Joseph Kosinski",
      genre: "Action",
      videoId: "giXco2jaZ_4",
    },
    {
      id: 17,
      name: "Train to Busan Presents: Peninsula",
      image: "https://i.ytimg.com/vi/yVucSRLLeIM/hqdefault.jpg",
      description: "Four years after a zombie outbreak ravaged South Korea, ex-soldier Jung-seok joins a rogue team to infiltrate the infested peninsula and retrieve a truckload of cash. Landing in a desolate Incheon, they face hordes of ravenous undead and a rogue militia led by a deranged commander. Teaming with survivors Min-jung and her daughters, Jung-seok battles for redemption in high-octane chases and explosive showdowns. Director Yeon Sang-ho expands the *Train to Busan* universe with relentless action and gritty survival stakes. Gang Dong-won’s stoic lead drives this thrilling, post-apocalyptic ride.",
      releaseDate: "2020-07-15",
      director: "Yeon Sang-ho",
      genre: "Action",
      videoId: "P8nZ3vK7xRt",
    },
    {
      id: 18,
      name: "Marco",
      image: "https://i.ytimg.com/vi/AdwGOloQcAs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDEtfoXZcXEm5Ahov3MmYvvD_5tdQ",
      description: "Marco Jr., a ruthless gangster raised in the violent underworld of Kochi, inherits his father Victor’s criminal empire after a brutal betrayal. Driven by vengeance, he wages a bloody war against rival syndicates and corrupt cops, carving a path of destruction with his unmatched combat skills. As loyalties fracture and secrets unravel, Marco’s quest for power tests his humanity in a city soaked in chaos. Director Haneef Adeni delivers a raw, adrenaline-fueled spectacle, with Unni Mukundan’s ferocious lead performance anchoring this Malayalam action epic, pushing regional cinema’s boundaries into gritty, global territory.",
      releaseDate: "2021-12-20",
      director: "Haneef Adeni",
      genre: "Action",
      videoId: "M7qZ4vK9yTw",
    },
    {
      id: 34,
      name: "Venom: The Last Dance",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1sHa9CO9Tj_CfCSsN0UrUYk6ApcGngkDmRA&s",
      description: "Eddie Brock and his alien symbiote Venom are fugitives, hunted by a secretive government force after their chaotic past. As a monstrous invasion from Venom’s homeworld threatens Earth, the duo faces relentless mercenaries and a primal symbiote god, Knull’s wrath. Teaming with unlikely allies, Eddie battles for survival in explosive chases and visceral clashes, confronting their bond’s limits. Director Kelly Marcel closes the trilogy with a wild, emotional ride, blending dark humor and savage action. Tom Hardy’s raw dual performance anchors this comic-book epic, redefining Eddie and Venom’s legacy.",
      releaseDate: "2024-10-25",
      director: "Kelly Marcel",
      genre: "Action",
      videoId: "V8mZ3vK9xQw",
    },
    {
      id: 20,
      name: "Extraction",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY14x4RIxfG6RdW6luPDetHDJMNxgWAJQ5Qg&s",
      description: "A mercenary rescues a kidnapped child in a volatile city.",
      releaseDate: "2020-04-24",
      director: "Sam Hargrave",
      genre: "Action",
      videoId: "L6P3nI6VnlY",
    },
   
  ];

  export const adventureMovies = [
    {
        id: 1,
        name: "Alpha",
        image: "https://jiotvimages.cdn.jio.com/imagespublic/17/46/41a18a3625525714b1c02919f5bcbfd1_1735201863244_l_medium.jpg",
        description: "In the Ice Age, Keda, a young hunter, is left for dead after a bison hunt gone wrong, stranded in a harsh prehistoric wilderness. Facing starvation and predators, he forms a bond with a wounded wolf, Alpha, forging a partnership to survive. Their journey across treacherous landscapes tests courage and trust, leading to a triumphant return. Director Albert Hughes delivers a visceral survival epic, with Kodi Smit-McPhee’s raw portrayal illuminating this primal adventure of man and nature’s uneasy alliance.",
        releaseDate: "2018-08-17",
        director: "Albert Hughes",
        genre: "Adventure",
        videoId: "R7mZ3vK9xQw",
      },
      {
        id: 2,
        name: "Ne Zha",
        image: "https://i.ytimg.com/vi/wnNOJeAYuBE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBoKwf2N3MNinM4S0xC2QcJTDNI6g",
        description: "Born from a heavenly pearl as a demon child, Ne Zha faces a prophecy foretelling his world’s destruction. Outcast and feared in Chentang Pass, he battles his demonic nature under the guidance of Taoist master Taiyi Zhenren. When rival Ao Bing, born of a spirit pearl, becomes his foe, Ne Zha’s journey tests his choice between good and evil. With stunning animation and emotional depth, director Jiaozi reimagines the Chinese myth from *Investiture of the Gods*, with Lü Yanting’s spirited voice leading this epic adventure of fate, sacrifice, and redemption.",
        releaseDate: "2019-07-13",
        director: "Jiaozi",
        genre: "Adventure",
        videoId: "H9qZ5vJ8r3Y",
      },
      {
        id: 3,
        name: "The Hobbit: An Unexpected Journey",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9tnxOrsiru4_hiSOJ6QBq5y49OsZ57zf7tw&s",
        description: "Bilbo Baggins, a timid hobbit, joins Gandalf and a band of dwarves, led by Thorin Oakenshield, to reclaim Erebor from the dragon Smaug. Their perilous trek through Middle-earth faces trolls, goblins, and a riddle game with Gollum, testing Bilbo’s courage. The discovery of a Ring sets a grander fate in motion. Director Peter Jackson adapts Tolkien’s prelude with Martin Freeman’s endearing Bilbo, launching a sweeping adventure of bravery and destiny in a richly imagined realm.",
        releaseDate: "2012-12-14",
        director: "Peter Jackson",
        genre: "Adventure",
        videoId: "E7qZ4vK9yTw",
      },
   
    {
      id: 4,
      name: "Dune: Part Two",
      image: "https://i.ytimg.com/vi/53BBRKF-L60/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGH8gQygTMA8=&rs=AOn4CLDgS78KBd_b20u0o-YBvLDGs6De2A",
      description: "Paul Atreides, heir to a noble house, rises among the Fremen of Arrakis after his family’s betrayal. Mastering the desert’s ways and a messianic prophecy, he leads a revolt against the tyrannical Harkonnens to control the spice trade. With Chani by his side, Paul’s visions of war clash with his desire for peace in epic battles across dunes. Denis Villeneuve’s stunning sequel, starring Timothée Chalamet, expands Herbert’s saga into a sweeping adventure of power, destiny, and ecological struggle.",
      releaseDate: "2024-03-01",
      director: "Denis Villeneuve",
      genre: "Adventure",
      videoId: "L8mZ3vK9yTw",
    },
    {
      id: 5,
      name: "The Lion King",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsdpWDh0aHIl_QtUjbZ_UC71BBJo6RK2G33g&s",
      description: "Simba, a young lion cub, flees his pride after his father Mufasa’s murder by his uncle Scar, who usurps the throne. Guided by friends Timon and Pumbaa, Simba grows in exile, wrestling with guilt and destiny. Returning to reclaim Pride Rock, he battles Scar in a dramatic showdown to restore balance. Jon Favreau’s photorealistic remake of Disney’s classic, with James Earl Jones and Beyoncé, delivers a heartfelt adventure of courage, family, and redemption in the African savanna.",
      releaseDate: "2019-07-19",
      director: "Jon Favreau",
      genre: "Adventure",
      videoId: "M7qZ4vK9xRt",
    },
    {
      id: 6,
      name: "Moana",
      image: "https://coldspringharbor.librarycalendar.com/sites/default/files/2022-07/Moana-Movie-Poster-landscape-1024x461.jpg",
      description: "Moana, a Polynesian teen, defies her village’s boundaries to save her people from a blight, guided by the ocean’s call. Teaming with demigod Maui, she sails treacherous seas, facing monsters like Te Kā to return a stolen heart to Te Fiti. Her journey uncovers her heritage and courage in vibrant, wave-tossed adventures. Directors Ron Clements and John Musker craft Disney’s animated triumph, with Auliʻi Cravalho’s spirited voice, celebrating exploration, identity, and resilience across the Pacific.",
      releaseDate: "2016-11-23",
      director: "Ron Clements, John Musker",
      genre: "Adventure",
      videoId: "N9qZ5vJ8r3Y",
    },
    {
      id: 7,
      name: "Sonic the Hedgehog: The Movie",
      image: "https://i.pinimg.com/736x/f4/32/df/f432dfa719ecd48214de35238cce27ae.jpg",
      description: "Sonic, a speedy hedgehog, teams with human Tom Wachowski to stop Dr. Robotnik’s plot to harness his power and dominate Earth. Racing through cities and forests, they face robotic armies and Robotnik’s cunning traps in a high-energy chase. Sonic’s quest for belonging fuels their unlikely alliance in a battle for freedom. Directors Jeff Fowler and Tim Miller bring Sega’s icon to life, with Ben Schwartz’s witty voice, delivering a family-friendly adventure packed with humor and supersonic thrills.",
      releaseDate: "2020-02-14",
      director: "Jeff Fowler",
      genre: "Adventure",
      videoId: "O8mZ3vK9xQw",
    },
    {
      id: 8,
      name: "Jurassic World Dominion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkh_J3iw7J8pMWu2hW74SptFfUCbksYaQCvw&s",
      description: "Dinosaurs roam a world shared with humans after Jurassic World’s collapse, sparking a global crisis. Owen Grady and Claire Dearing race to rescue Maisie Lockwood from a biotech firm exploiting dinosaurs, facing raptors and a giant locust plague. Their journey across continents pits survival against greed in epic chases and prehistoric battles. Director Colin Trevorrow concludes the saga with Chris Pratt and Bryce Dallas Howard, blending awe and danger in a thrilling adventure that redefines humanity’s place with nature.",
      releaseDate: "2022-06-10",
      director: "Colin Trevorrow",
      genre: "Adventure",
      videoId: "P7qZ4vK9yTw",
    },
    {
      id: 9,
      name: "Azaad",
      image: "https://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2025/01/13/ghkrmiqboaa5uwk1964711.jpg?w=777&crop=0,10,777px,437px",
      description: "In this 1955 Indian classic, Azaad, a noble bandit, roams the deserts of Rajasthan, aiding the oppressed while evading British rule. Disguised as a prince, he rescues Shobha from a forced marriage, sparking a daring chase across rugged terrains. His loyalty and courage shine as he battles corrupt officials and rival gangs, seeking justice for the downtrodden. Director S.M. Sriramulu Naidu crafts a swashbuckling tale of honor, with Dilip Kumar’s charismatic performance driving this timeless adventure of rebellion and romance in a vibrant, lawless land.",
      releaseDate: "1955-01-07",
      director: "S.M. Sriramulu Naidu",
      genre: "Adventure",
      videoId: "Q9qZ5vJ8r3Y",
    },
    {
        id: 10,
        name: "Inception",
        image: "https://images7.alphacoders.com/518/518783.jpg",
        description: "Dom Cobb, a skilled thief, infiltrates dreams to steal secrets for corporate espionage. Offered a chance to reclaim his life by planting an idea in a billionaire’s mind, he leads a team into layered dream worlds where reality blurs. Facing armed projections and subconscious defenses, Cobb battles guilt over his lost wife as the mission teeters on collapse. Christopher Nolan crafts a mind-bending adventure of deception and identity, with Leonardo DiCaprio’s haunted lead driving this Oscar-winning sci-fi epic that redefines cinematic storytelling.",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        genre: "Adventure",
        videoId: "I9qZ5vJ8r3Y",
      },
      {
        id: 11,
        name: "Interstellar",
        image: "https://m.media-amazon.com/images/I/61S2XaBPy6L._AC_UF894,1000_QL80_.jpg",
        description: "In a dying Earth, ex-astronaut Cooper leads a desperate mission through a wormhole to find a new home for humanity. Navigating uncharted planets with his crew, he confronts black holes, time dilation, and the sacrifices of love. Guided by cryptic messages from his daughter, Cooper’s journey tests human resilience against cosmic odds. Christopher Nolan’s visionary tale blends science and emotion, with Matthew McConaughey’s heartfelt performance anchoring this space odyssey, exploring survival and legacy in a breathtaking adventure.",
        releaseDate: "2014-11-07",
        director: "Christopher Nolan",
        genre: "Adventure",
        videoId: "J7mZ3vK9xQw",
      },
    {
      id: 12,
      name: "Jurassic World",
      image: "https://imageio.forbes.com/blogs-images/scottmendelson/files/2018/06/jurassic-world-2B-1200x594.jpg?format=jpg&height=600&width=1200&fit=bounds",
      description: "On Isla Nublar, Jurassic World’s genetically engineered dinosaurs, including the Indominus rex, break free, threatening tourists and staff. Owen Grady, a raptor trainer, teams with Claire Dearing to contain the chaos, racing through jungles and labs to save lives. Their mission uncovers corporate greed behind the park’s downfall. Director Colin Trevorrow crafts a thrilling revival of the franchise, with Chris Pratt and Bryce Dallas Howard leading this prehistoric adventure of survival, wonder, and the perils of playing god with nature.",
      releaseDate: "2015-06-12",
      director: "Colin Trevorrow",
      genre: "Adventure",
      videoId: "T7qZ4vK9xRt",
    },
    {
      id: 13,
      name: "Life of Pi",
      image: "https://c4.wallpaperflare.com/wallpaper/672/360/13/5bd4a9d93f219-wallpaper-preview.jpg",
      description: "Pi Patel, a young Indian boy, survives a shipwreck, adrift on a lifeboat with a Bengal tiger, Richard Parker, in the Pacific Ocean. Facing storms, starvation, and the tiger’s threat, Pi’s journey becomes a test of faith and resilience across endless waters. Through vivid hallucinations and survival tactics, he finds meaning in the wild. Director Ang Lee adapts Yann Martel’s novel into a mesmerizing adventure, with Suraj Sharma’s soulful performance illuminating this tale of hope and human-animal connection.",
      releaseDate: "2012-11-21",
      director: "Ang Lee",
      genre: "Adventure",
      videoId: "U9qZ5vJ8r3Y",
    },
    {
      id: 14,
      name: "The Great Wall",
      image: "https://guysgurugrades.wordpress.com/wp-content/uploads/2017/02/the-great-wall-poster.jpg",
      description: "In 11th-century China, mercenary William Garin joins the Nameless Order defending the Great Wall from monstrous Tao Tei invaders. Captured with Pero Tovar, he fights alongside General Lin Mae in epic battles, using innovative tactics to protect the empire. Their quest uncovers ancient secrets amid the wall’s grandeur. Director Zhang Yimou blends historical spectacle with fantasy, starring Matt Damon in a visually stunning adventure of courage, cultural clash, and humanity’s stand against otherworldly forces.",
      releaseDate: "2016-12-16",
      director: "Zhang Yimou",
      genre: "Adventure",
      videoId: "V8mZ3vK9xQw",
    },
    {
      id: 15,
      name: "Spectral",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00036170-bwlxaufzhr-landscape.jpg",
      description: "In a war-torn Moldova, DARPA scientist Mark Clyne investigates ghostly specters decimating U.S. troops. Teaming with a special forces unit, he uncovers a Soviet experiment gone awry, leading to intense combat in a spectral-infested city. Their mission to neutralize the threat blends technology with bravery across ruined streets. Director Nic Mathieu crafts a tense, sci-fi adventure, with James Badge Dale’s determined lead driving this military thriller into uncharted supernatural territory.",
      releaseDate: "2016-12-09",
      director: "Nic Mathieu",
      genre: "Adventure",
      videoId: "W7qZ4vK9yTw",
    },
    {
      id: 16,
      name: "Warcraft",
      image: "https://m.media-amazon.com/images/M/MV5BMTY2NzQ1NTg1NV5BMl5BanBnXkFtZTgwNjE2MzA3ODE@._V1_.jpg",
      description: "When the orcish Horde invades Azeroth through a portal, human guardian Anduin Lothar and mage Khadgar ally with orc defector Durotan to prevent war. Battles rage across mystical lands, blending magic and might as both sides seek survival. Their uneasy truce tests loyalty in a clash of worlds. Director Duncan Jones adapts Blizzard’s game into a sweeping adventure, with Travis Fimmel and Toby Kebbell leading this epic tale of honor and conflict in a fantasy realm.",
      releaseDate: "2016-06-10",
      director: "Duncan Jones",
      genre: "Adventure",
      videoId: "X9qZ5vJ8r3Y",
    },
    {
      id: 17,
      name: "Man of Steel",
      image: "https://c4.wallpaperflare.com/wallpaper/438/958/473/2013-man-of-steel-hd-man-of-steel-poster-wallpaper-preview.jpg",
      description: "Kal-El, raised as Clark Kent on Earth, discovers his Kryptonian heritage as a planet-destroying threat looms. Battling General Zod, he harnesses superhuman strength and flight to protect humanity, grappling with his dual identity. His journey across cities and skies defines a hero’s rise. Director Zack Snyder reimagines Superman’s origin, with Henry Cavill’s powerful portrayal anchoring this action-packed adventure of destiny, sacrifice, and the birth of a modern icon.",
      releaseDate: "2013-06-14",
      director: "Zack Snyder",
      genre: "Adventure",
      videoId: "Y8mZ3vK9xQw",
    },
    {
      id: 18,
      name: "The Revenant",
      image: "https://paulist.org/app/uploads/2016/02/Revenant.jpg",
      description: "Hugh Glass, a frontiersman, is mauled by a bear and left for dead by his 1820s fur-trapping crew in the unforgiving American wilderness. Driven by vengeance against the traitor John Fitzgerald, Glass crawls through snow and rivers, enduring frostbite and starvation. His solitary quest for justice transforms into a test of survival and spirit. Director Alejandro G. Iñárritu crafts a visceral epic, with Leonardo DiCaprio’s grueling performance earning an Oscar, blending raw nature with a tale of human resilience and retribution.",
      releaseDate: "2015-12-25",
      director: "Alejandro G. Iñárritu",
      genre: "Adventure",
      videoId: "Z9qZ5vJ8r3Y",
    },
    {
      id: 19,
      name: "Mad Max: Fury Road",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO4Rn25dl7FyN2C0Ou7a7VE4WKo58Vp8w2eg&s",
      description: "In a post-apocalyptic wasteland, Max Rockatansky teams with Imperator Furiosa to escape a tyrannical warlord, Immortan Joe, who enslaves women for breeding. Their high-octane chase across deserts in a war rig faces sandstorms and relentless pursuers, fueled by a fight for freedom. The duo’s rebellion ignites a stunning spectacle of vehicular combat and survival. Director George Miller delivers a relentless, visually arresting adventure, with Tom Hardy and Charlize Theron leading this modern classic of action and redemption.",
      releaseDate: "2015-05-15",
      director: "George Miller",
      genre: "Adventure",
      videoId: "A8mZ3vK9xQw",
    },
    {
      id: 20,
      name: "The Martian",
      image: "https://mir-s3-cdn-cf.behance.net/projects/404/d06db0120605581.Y3JvcCw4NDIsNjU4LDAsMA.jpg",
      description: "Astronaut Mark Watney is stranded on Mars after a storm forces his crew to abandon him, presumed dead. Using science and ingenuity, he cultivates potatoes and signals NASA for rescue, battling isolation and resource scarcity. His survival odyssey inspires a global effort to bring him home across the red planet’s harsh terrain. Director Ridley Scott crafts a gripping space adventure, with Matt Damon’s witty resilience anchoring this tale of human perseverance and the triumph of intellect over adversity.",
      releaseDate: "2015-10-02",
      director: "Ridley Scott",
      genre: "Adventure",
      videoId: "B7qZ4vK9yTw",
    },
    {
      id: 21,
      name: "Pirates of the Caribbean: The Curse of the Black Pearl",
      image: "https://images.squarespace-cdn.com/content/v1/5b18735a3917ee20d18a2117/f96bf719-5573-4c0b-85ac-a40495028dc6/scale.jpg",
      description: "Captain Jack Sparrow seeks to reclaim his ship, the Black Pearl, hijacked by mutineer Barbossa, whose cursed crew turns skeletal under moonlight. Teaming with Will Turner and Elizabeth Swann, Jack navigates treacherous seas, battling undead pirates for a cursed Aztec gold. Their swashbuckling quest blends humor and danger across Caribbean waters. Director Gore Verbinski launches a franchise with Johnny Depp’s iconic Sparrow leading this rollicking adventure of greed, loyalty, and supernatural intrigue.",
      releaseDate: "2003-07-09",
      director: "Gore Verbinski",
      genre: "Adventure",
      videoId: "C9qZ5vJ8r3Y",
    },
    {
      id: 22,
      name: "Avatar",
      image: "https://c4.wallpaperflare.com/wallpaper/810/33/235/movies-avatar-1680x1050-entertainment-movies-hd-art-wallpaper-preview.jpg",
      description: "Jake Sully, a paraplegic Marine, inhabits a Na’vi avatar on Pandora, a lush alien moon, to infiltrate its indigenous people for Earth’s resources. Falling for Neytiri, he joins the Na’vi against human colonizers, leading a rebellion in epic aerial battles. His journey transforms from espionage to defending a world of wonder. Director James Cameron revolutionizes cinema with this groundbreaking adventure, starring Sam Worthington, blending spectacle and environmental themes in a Pandora-spanning saga.",
      releaseDate: "2009-12-18",
      director: "James Cameron",
      genre: "Adventure",
      videoId: "D8mZ3vK9xQw",
    },
    {
        id: 23,
        name: "The Lord of the Rings: The Fellowship of the Ring",
        image: "https://dyn1.heritagestatic.com/lf?set=path%5B1%2F1%2F4%2F5%2F1%2F11451494%5D&call=url%5Bfile%3Aproduct.chain%5D",
        description: "In Middle-earth, hobbit Frodo Baggins inherits a Ring of power that could doom the world if wielded by the Dark Lord Sauron. Joining a diverse fellowship—Aragorn, Gandalf, and others—Frodo embarks on a perilous quest to destroy it in Mount Doom. Facing orcs, trolls, and inner doubts, their journey through stunning landscapes tests courage and unity. Peter Jackson’s epic adaptation of Tolkien’s saga, with Elijah Wood’s earnest Frodo, launches a legendary adventure of friendship and sacrifice that reshaped fantasy cinema.",
        releaseDate: "2001-12-19",
        director: "Peter Jackson",
        genre: "Adventure",
        videoId: "K5vJ9kZbX8Z",
      },
    {
      id: 24,
      name: "Journey to the West: The Demons Strike Back",
      image: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F4%2Fgracenote%2F407e98e253dfc6d1716c0e4b5a67becf.jpg",
      description: "Tang Sanzang and his disciples—Sun Wukong, Zhu Bajie, and Sha Wujing—continue their perilous quest to the West for Buddhist scriptures, facing new demonic threats. Amidst tensions with Wukong, blamed for a past loss, they battle spider demons, Red Boy, and the White Bone Spirit in a land of chaos. Their journey tests forgiveness and unity, culminating in a desert trek toward enlightenment. Directed by Tsui Hark with Stephen Chow’s influence, this sequel blends slapstick humor with dazzling action, starring Kris Wu and Lin Gengxin, delivering a whimsical yet epic conclusion to their saga.",
      releaseDate: "2017-01-28",
      director: "Tsui Hark",
      genre: "Adventure",
      videoId: "I8mZ3vK9xQw",
    },
    {
      id: 25,
      name: "Jumanji: Welcome to the Jungle",
      image: "https://rukminim2.flixcart.com/image/850/1000/jnc2bgw0/poster/q/k/j/medium-hollywood-movie-wall-poster-jumanji-welcome-to-the-jungle-original-imafayzgbdutkykt.jpeg?q=20&crop=false",
      description: "Four teens are sucked into a video game, transforming into adult avatars—Spencer as a brawny explorer, Martha as a martial artist—trapped in Jumanji’s jungle. Facing rhinos, a vengeful hunter, and puzzles, they must complete the game to escape. Their teamwork evolves from rivalry to camaraderie in a wild, danger-filled quest. Directors Jake Kasdan and Chris McKenna revive the franchise with Dwayne Johnson and Kevin Hart, delivering a hilarious, action-packed adventure of self-discovery and survival.",
      releaseDate: "2017-12-20",
      director: "Jake Kasdan",
      genre: "Adventure",
      videoId: "G8mZ3vK9xQw",
    },
];
export const trendingmovies = [
    {
        id: 1,
        name: "Marco",
        image: "https://origin-staticv2.sonyliv.com/videoasset_images/manage_file/1000000003/1739354930890624_MARCO_Landscape_Thumb.jpg",
        description: "Marco, a vengeful warrior, unleashes brutal fury to avenge his brother’s murder, carving a bloody path through betrayal and loss in a gritty 1920s underworld. His relentless quest redefines loyalty and sacrifice. Director Haneef Adeni delivers a raw, action-packed Malayalam epic in 2024, with Unni Mukundan leading a visceral saga of violence and redemption.",
        releaseDate: "2024-12-20",
        director: "Haneef Adeni",
        genre: "Action",
        videoId: "8zX9z7pL9Uc"
      },
      {
        id: 2,
        name: "Azaad",
        image: "https://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2025/01/13/ghkrmiqboaa5uwk1964711.jpg?w=777&crop=0,10,777px,437px",
        description: "In 1920s India, stable boy Govind bonds with a spirited horse, Azaad, igniting a daring quest against oppression. His race for freedom challenges tyranny and sparks forbidden love. Director Abhishek Kapoor crafts a heartfelt period drama in 2025, with Aaman Devgan and Rasha Thadani debuting in a tale of courage and rebellion.",
        releaseDate: "2025-01-17",
        director: "Abhishek Kapoor",
        genre: "Drama",
        videoId: "1hX4MpJALM"
      },
    {
        id: 3,
        name: "I Am Kathalan",
        image: "https://static.moviecrow.com/marquee/i-am-kathalan-review---an-interesting-technology-based-thriller/237504_thumb_665.jpg",
        description: "A young man’s quest for justice turns perilous as he infiltrates a criminal network, navigating Kerala’s shadows to expose corruption. His journey blends bravery with danger across urban and rural terrains. A tale of defiance emerges. Director [Unknown] stars Naslen K. Gafoor in this 2025 Malayalam thriller, delivering a gripping adventure of identity and retribution in a world of deceit.",
        releaseDate: "2025-03-14",
        director: "[Unknown]",
        genre: "Adventure",
        videoId: "A1mZ3vK9xQw",
      },
     
      {
        id: 5,
        name: "Chhaava",
        image: "https://images.filmibeat.com/ph-big/img_og/chhavva-movie-stils-on-set-pictures-poster-stills1724226886.jpg",
        description: "After Chhatrapati Shivaji Maharaj’s death in 1680, his son Sambhaji Maharaj, portrayed by Vicky Kaushal, rises to defend the Maratha Empire against Mughal emperor Aurangzeb, played by Akshaye Khanna. Facing betrayal and fierce battles, Sambhaji’s journey across Deccan forts tests his courage and leadership, seeking to honor his father’s legacy. A tale of valor unfolds amidst political intrigue. Directed by Laxman Utekar, this 2025 epic, with Rashmika Mandanna as Yesubai, blends stunning visuals and A.R. Rahman’s score, capturing Sambhaji’s defiant odyssey against overwhelming odds in a richly crafted historical landscape.",
        releaseDate: "2025-02-14",
        director: "Laxman Utekar",
        genre: "Adventure",
        videoId: "I2mZ3vK9xQw",
      },
      {
          id: 6,
          name: "Hyper Knife",
          image: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/2542/1732003122542-i",
          description: "Dr. Jung Se-ok, a disgraced neurosurgeon haunted by a past tragedy, embarks on a perilous journey into the shadows, performing illegal surgeries to reclaim her genius. Reunited with her mentor, Dr. Choi Deok-hee, who stripped her license, she navigates a dangerous game of revenge and power across Seoul’s underworld. Her quest for redemption and medical breakthroughs tests her morality amid high-stakes operations. Directed by Kim Jung-hyun, this 2025 Disney+ series, starring Park Eun-bin and Sul Kyung-gu, blends medical tension with a gripping odyssey of betrayal and resilience in a morally gray landscape.",
          releaseDate: "2025-03-19",
          director: "Kim Jung-hyun",
          genre: "Adventure",
          videoId: "K4mZ3vK9xQw",
        },
   
      {
        id: 7,
        name: "Solo Leveling Season 2",
        image: "https://4kwallpapers.com/images/wallpapers/solo-leveling-5120x2880-19518.png",
        description: "Sung Jinwoo, now a powerful Shadow Monarch, confronts the aftermath of the Jeju Island arc, facing new threats like the Monarchs of Fangs and Frost. His journey through dungeons and battles tests his growing strength and leadership, unraveling mysteries of his leveling system. A tale of ascension unfolds. Directed by Shunsuke Nakashige, this 2025 Crunchyroll hit, with Taito Ban voicing Jinwoo, builds on the Red Gate arc’s intensity, captivating fans with epic fights and a world-expanding odyssey of power and destiny.",
        releaseDate: "2025-01-04",
        director: "Shunsuke Nakashige",
        genre: "Adventure",
        videoId: "F1mZ3vK9xQw",
      },
      {
        id: 8,
        name: "Squid Game Season 2",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUVlbDLE1SLSehl8jEhRi4-lZFF8DQEEIIKA&s",
        description: "Seong Gi-hun returns to the deadly games, seeking revenge against the Front Man, navigating new challenges with higher stakes and unexpected allies. His journey through treacherous rounds tests survival and morality in a brutal arena. A gripping saga emerges. Directed by Hwang Dong-hyuk, this 2025 Netflix finale, starring Lee Jung-jae and Lee Byung-hun, builds on Season 1’s tension, delivering a climactic adventure of human resilience and sacrifice, set to conclude on June 27.",
        releaseDate: "2025-01-01",
        director: "Hwang Dong-hyuk",
        genre: "Adventure",
        videoId: "G7qZ4vK9yTw",
      },
    {
      id: 9,
      name: "Game Changer",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00311772-besdebnnvv-landscape.jpg",
      description: "An idealistic IAS officer battles corruption in a high-stakes political thriller, racing across urban and rural India to reform a tainted system. Facing assassins and betrayal, his journey tests integrity and courage. A tale of justice unfolds. Director Shankar directs Ram Charan in this 2025 Telugu action epic, blending political intrigue with explosive action, captivating audiences with a quest for change in a divided land.",
      releaseDate: "2025-01-10",
      director: "Shankar",
      genre: "Adventure",
      videoId: "X8mZ3vK9xQw",
    },
    {
        id: 10,
        name: "War for the Planet of the Apes",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvKSA9ut57bt4AJjv_P32_8ZTmCwpXSw1pHQ&s",
        description: "After suffering devastating losses, Caesar, the intelligent ape leader, embarks on a mythic quest for vengeance against the ruthless Colonel McCullough and his human army, Alpha-Omega. Leading his tribe through snowy wilderness and human captivity, Caesar wrestles with his darker instincts, seeking a new home amid a brutal war. A tale of survival and sacrifice unfolds. Directed by Matt Reeves, this 2017 epic, with Andy Serkis’ motion-captured Caesar and Woody Harrelson’s chilling Colonel, blends stunning visuals and Michael Giacchino’s score, delivering a poignant adventure that concludes the trilogy with a battle for Earth’s future.",
        releaseDate: "2017-07-14",
        director: "Matt Reeves",
        genre: "Adventure",
        videoId: "J3mZ3vK9xQw",
      },
    {
      id: 7,
      name: "My Fault: London",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbeezovuhyJlIIe7WMhoYiYXPWAdzszxOsKg&s",
      description: "Noah and Nick’s passionate romance faces new trials in London, where family secrets and rivalries ignite a dangerous chase across the city’s underworld. Their love-driven journey tests loyalty amid betrayal. A steamy saga unfolds. Director [Unknown] expands the Spanish franchise in 2025, with Nicole Wallace and Gabriel Guevara leading this emotional adventure, blending romance and suspense in a bustling urban landscape.",
      releaseDate: "2025-07-18",
      director: "[Unknown]",
      genre: "Adventure",
      videoId: "Z9qZ5vJ8r3Y",
    },

  ];
  export const scifiMovies = [
    
    {
        id: 1,
        name: "One Piece Season 1",
        image: "https://m.media-amazon.com/images/I/81QE2bYDgWL._AC_UF894,1000_QL80_.jpg",
        description: "Monkey D. Luffy, a boy with a rubber body, sets sail to find the One Piece and become the Pirate King, assembling his Straw Hat crew—Zoro, Nami, Usopp, and Sanji—across the East Blue. Their journey through stormy seas and pirate battles tests courage and camaraderie, seeking the treasure of the legendary Gol D. Roger. A tale of dreams unfolds. Directed by various, with Iñaki Godoy as Luffy, this 2023 Netflix hit adapts Eiichiro Oda’s manga, blending vibrant visuals and high-seas adventure in a world of endless possibilities.",
        releaseDate: "2023-08-31",
        director: "[Various]",
        genre: "Adventure",
        videoId: "M7mZ3vK9xQw",
      },
      
    {
      id: 2,
      name: "Avatar: Fire and Ash",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzPC66n7sK7GG4i9Wg7iCu__qZqdlEL7YJzw&s",
      description: "Jake Sully and Neytiri lead their Na’vi clan against a new human threat on Pandora, navigating fiery landscapes and cultural clashes. Their quest to protect their world tests unity and sacrifice in a visually stunning odyssey. A saga of resistance emerges. Director James Cameron delivers this 2025 blockbuster, expanding the franchise with Sam Worthington and Zoë Saldaña, pushing cinematic boundaries in a vibrant, perilous alien realm.",
      releaseDate: "2025-12-19",
      director: "James Cameron",
      genre: "Science Fiction",
      videoId: "M2qZ4vK9yTw",
    },
    {
      id: 3,
      name: "Tron: Ares",
      image: "https://4kwallpapers.com/images/wallpapers/tron-ares-poster-3440x1440-22060.jpg",
      description: "Ares, a rogue program, crosses from the digital grid to the real world, sparking humanity’s first AI encounter. His mission through neon-lit dangers tests trust and survival in a high-stakes chase. A cybernetic adventure unfolds. Director Joachim Rønning crafts this 2025 sequel, with Jared Leto leading alongside Greta Lee and Jeff Bridges, reimagining the franchise with cutting-edge visuals and a clash of worlds.",
      releaseDate: "2025-08-15",
      director: "Joachim Rønning",
      genre: "Science Fiction",
      videoId: "N3mZ3vK9xQw",
    },
    {
        id: 4,
        name: "Terminator: Dark Fate",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcKcXLC0IstwKfr7Ygw-StccRZAGATJ-kruQ&s",
        description: "In 2042, an augmented soldier Grace protects Dani Ramos from a relentless Rev-9 Terminator sent to kill her, joined by a battle-hardened Sarah Connor and a reformed T-800. Their perilous journey across Mexico and beyond tests survival against a new AI threat, Legion, replacing Skynet. A tale of defiance unfolds. Directed by Tim Miller, this 2019 epic, with Linda Hamilton, Arnold Schwarzenegger, and Mackenzie Davis, redefines the franchise, blending intense action and emotional stakes in a future where humanity’s fate hangs by a thread against a shapeshifting foe.",
        releaseDate: "2019-11-01",
        director: "Tim Miller",
        genre: "Adventure",
        videoId: "N8mZ3vK9xQw",
      },
    {
      id: 5,
      name: "Jurassic World Rebirth",
      image: "https://static1.cbrimages.com/wordpress/wp-content/uploads/2024/09/jurassic-world-rebirth.jpg",
      description: "Five years after *Dominion*, an expedition ventures into equatorial jungles to extract DNA from massive dinosaurs for a medical cure, facing primal threats. Their quest through uncharted lands tests science and survival. A prehistoric saga unfolds. Director Gareth Edwards crafts this 2025 thriller, with Scarlett Johansson and Jonathan Bailey leading, reviving the franchise with stunning visuals and high-stakes adventure.",
      releaseDate: "2025-07-02",
      director: "Gareth Edwards",
      genre: "Science Fiction",
      videoId: "P5mZ3vK9xQw",
    },
    {
      id: 6,
      name: "Alien: Earth",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5u90CkbpId838GpHDiEnzuL0En43IdqBbDfcd4-6MgQnklUoDH6Y__1LnKqdLHu3GoKQ&usqp=CAU",
      description: "In 2120, soldiers discover a crashed alien vessel, uncovering the first Xenomorph on Earth, two years before *Alien*. Their mission through ruins tests bravery against cosmic horror. A chilling odyssey emerges. Creator Noah Hawley crafts this 2025 FX/Hulu series, with Sydney Chandler leading, redefining the franchise with suspense and corporate intrigue in a bleak future.",
      releaseDate: "2025-06-20",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "Q6qZ4vK9yTw",
    },
    {
        id: 7,
        name: "Inception",
        image: "https://images7.alphacoders.com/518/518783.jpg",
        description: "Dom Cobb, a skilled thief, infiltrates dreams to steal secrets for corporate espionage. Offered a chance to reclaim his life by planting an idea in a billionaire’s mind, he leads a team into layered dream worlds where reality blurs. Facing armed projections and subconscious defenses, Cobb battles guilt over his lost wife as the mission teeters on collapse. Christopher Nolan crafts a mind-bending adventure of deception and identity, with Leonardo DiCaprio’s haunted lead driving this Oscar-winning sci-fi epic that redefines cinematic storytelling.",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        genre: "Adventure",
        videoId: "I9qZ5vJ8r3Y",
      },
      {
        id: 8,
        name: "All of Us Are Dead Season 1",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL-eWCL9ax97vmVzoMpC5JTc9yMavvL8qMIQ&s",
        description: "At Hyosan High School, students face a sudden zombie outbreak sparked by a lab experiment gone awry, turning classmates into rabid threats. Led by Nam On-jo and Lee Cheong-san, they fight through classrooms and rooftops, seeking escape amid chaos and evolving hybrid zombies. Their journey tests bravery and bonds in a desperate bid for survival. A harrowing odyssey unfolds. Directed by Lee Jae-kyoo, this 2022 Netflix hit, starring Park Ji-hu and Yoon Chan-young, adapts Joo Dong-geun’s webtoon with gripping tension and emotional depth in a blood-soaked school turned battleground.",
        releaseDate: "2022-01-28",
        director: "Lee Jae-kyoo",
        genre: "Adventure",
        videoId: "O9mZ3vK9xQw",
      },
    {
      id: 9,
      name: "Blade Runner 2099",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuPBO3m_LYb9Vw8mbnV7Sc7oyKXR0LdgTBnA&s",
      description: "In a neon-drenched future, new blade runners hunt replicants, navigating a world of memory and identity. Their quest through urban decay tests humanity’s limits. A cyberpunk odyssey unfolds. Creator Silka Luisa crafts this 2025 Amazon series, with Michelle Yeoh and Hunter Schafer, expanding the franchise with atmospheric tension and philosophical depth.",
      releaseDate: "2025-11-07",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "T9mZ3vK9xQw",
    },
    {
      id: 10,
      name: "Andor Season 2",
      image: "https://heroichollywood.com/wp-content/uploads/2025/03/diego-luna-andor-season-2-logo.jpg",
      description: "Cassian Andor’s rebellion deepens over four years leading to *Rogue One*, facing espionage and Imperial forces. His journey through gritty worlds tests sacrifice and resolve. A rebel saga emerges. Creator Tony Gilroy crafts this 2025 Disney+ series, with Diego Luna and Ben Mendelsohn, delivering a tense sci-fi thriller in the *Star Wars* universe.",
      releaseDate: "2025-04-22",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "U0qZ4vK9yTw",
    },
    {
      id: 11,
      name: "Dune: Part Two",
      image: "https://w0.peakpx.com/wallpaper/273/831/HD-wallpaper-dune-part-two-poster.jpg",
      description: "Paul Atreides unites with the Fremen to avenge his family on Arrakis, mastering sandworm riding amid political intrigue. His quest through deserts tests destiny and power. An epic unfolds. Director Denis Villeneuve crafts this 2024 sci-fi masterpiece, with Timothée Chalamet and Zendaya, expanding Frank Herbert’s vision with breathtaking scope and tension.",
      releaseDate: "2024-03-01",
      director: "Denis Villeneuve",
      genre: "Science Fiction",
      videoId: "V1mZ3vK9xQw",
    },
    {
      id: 12,
      name: "Interstellar",
      image: "https://m.media-amazon.com/images/I/61S2XaBPy6L._AC_UF894,1000_QL80_.jpg",
      description: "A crew ventures beyond our galaxy to find a new home as Earth dies, navigating wormholes and icy planets. Their journey tests love and science in a cosmic odyssey. A profound tale emerges. Director Christopher Nolan crafts this 2014 classic, with Matthew McConaughey and Anne Hathaway, blending realism and spectacle in a timeless space epic.",
      releaseDate: "2014-11-07",
      director: "Christopher Nolan",
      genre: "Science Fiction",
      videoId: "W2qZ5vJ8r3Y",
    },
    {
      id: 13,
      name: "The Matrix",
      image: "https://rukminim3.flixcart.com/image/850/1000/juk4gi80/poster/h/c/q/large-newposter8930-wall-poster-movies-the-matrix-poster-large-original-imaf5tgtzvb8pdpc.jpeg?q=20&crop=false",
      description: "Neo awakens to a simulated reality, joining Morpheus and Trinity to fight machines controlling humanity. His journey through code and combat tests reality and freedom. A revolutionary saga unfolds. Directors Lana and Lilly Wachowski craft this 1999 landmark, with Keanu Reeves and Laurence Fishburne, redefining sci-fi with groundbreaking action and philosophy.",
      releaseDate: "1999-03-31",
      director: "Lana Wachowski, Lilly Wachowski",
      genre: "Science Fiction",
      videoId: "X3mZ3vK9xQw",
    },
    {
      id: 14,
      name: "Monster Hunt 2",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00071452-jqkpgvfkjm-landscape.jpg",
      description: "Wuba, the monster prince, embarks on a perilous journey after parting from his human parents, Tian and Lan, as a sinister dark lord seeks to eliminate him. Befriending gambler Tu Sigu, Wuba navigates monster realms and human dangers, while Tian and Lan race to rescue him from a heavy bounty. Their quest tests courage and family bonds across vibrant landscapes. A whimsical odyssey unfolds. Directed by Raman Hui, this 2018 Chinese epic, with Tony Leung Chiu-wai and Bai Baihe, dazzles with stunning visuals and humor in a world where monsters and humans collide in a battle for peace.",
      releaseDate: "2018-02-16",
      director: "Raman Hui",
      genre: "Adventure",
      videoId: "P0mZ3vK9xQw",
    },
    {
      id: 15,
      name: "Arrival",
      image: "https://images6.alphacoders.com/112/1121126.jpg",
      description: "Linguist Louise Banks decodes an alien language to avert global conflict, journeying into their ships’ mysteries. Her quest tests communication and time in a cerebral odyssey. A profound tale emerges. Director Denis Villeneuve crafts this 2016 gem, with Amy Adams and Jeremy Renner, blending science and emotion in a first-contact masterpiece.",
      releaseDate: "2016-11-11",
      director: "Denis Villeneuve",
      genre: "Science Fiction",
      videoId: "Z5mZ3vK9xQw",
    },
    {
      id: 16,
      name: "Ex Machina",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/hd/004e5197949939.5ed0f9ac04c75.jpg",
      description: "Programmer Caleb tests AI Ava in a secluded retreat, uncovering her creator’s dark intentions. His journey into artificial consciousness tests ethics and desire. A tense odyssey unfolds. Director Alex Garland crafts this 2014 thriller, with Alicia Vikander and Domhnall Gleeson, exploring AI’s humanity in a sleek, suspenseful sci-fi narrative.",
      releaseDate: "2014-01-21",
      director: "Alex Garland",
      genre: "Science Fiction",
      videoId: "A6qZ5vJ8r3Y",
    },
    {
      id: 17,
      name: "Annihilation",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00062635-qqtcvsbbyw-landscape.jpg",
      description: "A biologist joins an expedition into a shimmering zone where nature mutates, seeking her lost husband. Her journey through alien landscapes tests sanity and survival. A surreal saga emerges. Director Alex Garland crafts this 2018 film, with Natalie Portman and Jennifer Jason Leigh, blending horror and sci-fi in a visually arresting exploration.",
      releaseDate: "2018-02-23",
      director: "Alex Garland",
      genre: "Science Fiction",
      videoId: "B7mZ3vK9xQw",
    },
    {
      id: 18,
      name: "Stranger Things Season 4",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/8a6a68144592045.628efcd3e77b5.jpg",
      description: "The Hawkins gang battles a supernatural threat from the Upside Down, with Eleven regaining her powers across dimensions. Their journey tests friendship amid horror. A thrilling odyssey emerges. The Duffer Brothers craft this 2022 Netflix hit, with Millie Bobby Brown and Finn Wolfhard, expanding the sci-fi saga with ’80s nostalgia and epic stakes.",
      releaseDate: "2022-05-27",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "C8qZ4vK9yTw",
    },
    {
      id: 19,
      name: "Severance Season 1",
      image: "https://resizing.flixster.com/_nZgYtA0npPZtBfx-Njc3y7YPOs=/fit-in/1152x864/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p21271543_b_h8_aa.jpg",
      description: "Mark Scout navigates a corporate world where memories split between work and life, uncovering a sinister plot. His journey through mind games tests identity and truth. A cerebral odyssey unfolds. Creator Ben Stiller crafts this 2022 Apple TV+ series, with Adam Scott and Zach Cherry, blending dystopian sci-fi with psychological depth.",
      releaseDate: "2022-02-18",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "D9mZ3vK9xQw",
    },
    {
      id: 20,
      name: "The Expanse Season 5",
      image: "https://static1.colliderimages.com/wordpress/wp-content/uploads/2021/11/the-expanse-s5-recap.jpg",
      description: "The crew of the *Rocinante* battles a protomolecule threat across the solar system, navigating political chaos. Their journey tests loyalty in a sprawling sci-fi epic. A galactic saga emerges. Directors [Various] craft this 2020 Amazon series, with Steven Strait and Dominique Tipper, delivering a gritty, space-faring adventure with rich world-building.",
      releaseDate: "2020-12-16",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "E0qZ5vJ8r3Y",
    },
  ];