export const scifiMovies = [
    
    {
        id: 1,
        name: "One Piece Season 1",
        image: "https://m.media-amazon.com/images/I/81QE2bYDgWL._AC_UF894,1000_QL80_.jpg",
        description: "Monkey D. Luffy, a boy with a rubber body, sets sail to find the One Piece and become the Pirate King, assembling his Straw Hat crew—Zoro, Nami, Usopp, and Sanji—across the East Blue. Their journey through stormy seas and pirate battles tests courage and camaraderie, seeking the treasure of the legendary Gol D. Roger. A tale of dreams unfolds. Directed by various, with Iñaki Godoy as Luffy, this 2023 Netflix hit adapts Eiichiro Oda’s manga, blending vibrant visuals and high-seas adventure in a world of endless possibilities.",
        releaseDate: "2023-08-31",
        director: "[Various]",
        genre: "Adventure",
        videoId: "M7mZ3vK9xQw",
      },
      
    {
      id: 2,
      name: "Avatar: Fire and Ash",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzPC66n7sK7GG4i9Wg7iCu__qZqdlEL7YJzw&s",
      description: "Jake Sully and Neytiri lead their Na’vi clan against a new human threat on Pandora, navigating fiery landscapes and cultural clashes. Their quest to protect their world tests unity and sacrifice in a visually stunning odyssey. A saga of resistance emerges. Director James Cameron delivers this 2025 blockbuster, expanding the franchise with Sam Worthington and Zoë Saldaña, pushing cinematic boundaries in a vibrant, perilous alien realm.",
      releaseDate: "2025-12-19",
      director: "James Cameron",
      genre: "Science Fiction",
      videoId: "M2qZ4vK9yTw",
    },
    {
      id: 3,
      name: "Tron: Ares",
      image: "https://4kwallpapers.com/images/wallpapers/tron-ares-poster-3440x1440-22060.jpg",
      description: "Ares, a rogue program, crosses from the digital grid to the real world, sparking humanity’s first AI encounter. His mission through neon-lit dangers tests trust and survival in a high-stakes chase. A cybernetic adventure unfolds. Director Joachim Rønning crafts this 2025 sequel, with Jared Leto leading alongside Greta Lee and Jeff Bridges, reimagining the franchise with cutting-edge visuals and a clash of worlds.",
      releaseDate: "2025-08-15",
      director: "Joachim Rønning",
      genre: "Science Fiction",
      videoId: "N3mZ3vK9xQw",
    },
    {
        id: 4,
        name: "Terminator: Dark Fate",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcKcXLC0IstwKfr7Ygw-StccRZAGATJ-kruQ&s",
        description: "In 2042, an augmented soldier Grace protects Dani Ramos from a relentless Rev-9 Terminator sent to kill her, joined by a battle-hardened Sarah Connor and a reformed T-800. Their perilous journey across Mexico and beyond tests survival against a new AI threat, Legion, replacing Skynet. A tale of defiance unfolds. Directed by Tim Miller, this 2019 epic, with Linda Hamilton, Arnold Schwarzenegger, and Mackenzie Davis, redefines the franchise, blending intense action and emotional stakes in a future where humanity’s fate hangs by a thread against a shapeshifting foe.",
        releaseDate: "2019-11-01",
        director: "Tim Miller",
        genre: "Adventure",
        videoId: "N8mZ3vK9xQw",
      },
    {
      id: 5,
      name: "Jurassic World Rebirth",
      image: "https://static1.cbrimages.com/wordpress/wp-content/uploads/2024/09/jurassic-world-rebirth.jpg",
      description: "Five years after *Dominion*, an expedition ventures into equatorial jungles to extract DNA from massive dinosaurs for a medical cure, facing primal threats. Their quest through uncharted lands tests science and survival. A prehistoric saga unfolds. Director Gareth Edwards crafts this 2025 thriller, with Scarlett Johansson and Jonathan Bailey leading, reviving the franchise with stunning visuals and high-stakes adventure.",
      releaseDate: "2025-07-02",
      director: "Gareth Edwards",
      genre: "Science Fiction",
      videoId: "P5mZ3vK9xQw",
    },
    {
      id: 6,
      name: "Alien: Earth",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5u90CkbpId838GpHDiEnzuL0En43IdqBbDfcd4-6MgQnklUoDH6Y__1LnKqdLHu3GoKQ&usqp=CAU",
      description: "In 2120, soldiers discover a crashed alien vessel, uncovering the first Xenomorph on Earth, two years before *Alien*. Their mission through ruins tests bravery against cosmic horror. A chilling odyssey emerges. Creator Noah Hawley crafts this 2025 FX/Hulu series, with Sydney Chandler leading, redefining the franchise with suspense and corporate intrigue in a bleak future.",
      releaseDate: "2025-06-20",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "Q6qZ4vK9yTw",
    },
    {
        id: 7,
        name: "Inception",
        image: "https://images7.alphacoders.com/518/518783.jpg",
        description: "Dom Cobb, a skilled thief, infiltrates dreams to steal secrets for corporate espionage. Offered a chance to reclaim his life by planting an idea in a billionaire’s mind, he leads a team into layered dream worlds where reality blurs. Facing armed projections and subconscious defenses, Cobb battles guilt over his lost wife as the mission teeters on collapse. Christopher Nolan crafts a mind-bending adventure of deception and identity, with Leonardo DiCaprio’s haunted lead driving this Oscar-winning sci-fi epic that redefines cinematic storytelling.",
        releaseDate: "2010-07-16",
        director: "Christopher Nolan",
        genre: "Adventure",
        videoId: "I9qZ5vJ8r3Y",
      },
      {
        id: 8,
        name: "All of Us Are Dead Season 1",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL-eWCL9ax97vmVzoMpC5JTc9yMavvL8qMIQ&s",
        description: "At Hyosan High School, students face a sudden zombie outbreak sparked by a lab experiment gone awry, turning classmates into rabid threats. Led by Nam On-jo and Lee Cheong-san, they fight through classrooms and rooftops, seeking escape amid chaos and evolving hybrid zombies. Their journey tests bravery and bonds in a desperate bid for survival. A harrowing odyssey unfolds. Directed by Lee Jae-kyoo, this 2022 Netflix hit, starring Park Ji-hu and Yoon Chan-young, adapts Joo Dong-geun’s webtoon with gripping tension and emotional depth in a blood-soaked school turned battleground.",
        releaseDate: "2022-01-28",
        director: "Lee Jae-kyoo",
        genre: "Adventure",
        videoId: "O9mZ3vK9xQw",
      },
    {
      id: 9,
      name: "Blade Runner 2099",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuPBO3m_LYb9Vw8mbnV7Sc7oyKXR0LdgTBnA&s",
      description: "In a neon-drenched future, new blade runners hunt replicants, navigating a world of memory and identity. Their quest through urban decay tests humanity’s limits. A cyberpunk odyssey unfolds. Creator Silka Luisa crafts this 2025 Amazon series, with Michelle Yeoh and Hunter Schafer, expanding the franchise with atmospheric tension and philosophical depth.",
      releaseDate: "2025-11-07",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "T9mZ3vK9xQw",
    },
    {
      id: 10,
      name: "Andor Season 2",
      image: "https://heroichollywood.com/wp-content/uploads/2025/03/diego-luna-andor-season-2-logo.jpg",
      description: "Cassian Andor’s rebellion deepens over four years leading to *Rogue One*, facing espionage and Imperial forces. His journey through gritty worlds tests sacrifice and resolve. A rebel saga emerges. Creator Tony Gilroy crafts this 2025 Disney+ series, with Diego Luna and Ben Mendelsohn, delivering a tense sci-fi thriller in the *Star Wars* universe.",
      releaseDate: "2025-04-22",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "U0qZ4vK9yTw",
    },
    {
      id: 11,
      name: "Dune: Part Two",
      image: "https://w0.peakpx.com/wallpaper/273/831/HD-wallpaper-dune-part-two-poster.jpg",
      description: "Paul Atreides unites with the Fremen to avenge his family on Arrakis, mastering sandworm riding amid political intrigue. His quest through deserts tests destiny and power. An epic unfolds. Director Denis Villeneuve crafts this 2024 sci-fi masterpiece, with Timothée Chalamet and Zendaya, expanding Frank Herbert’s vision with breathtaking scope and tension.",
      releaseDate: "2024-03-01",
      director: "Denis Villeneuve",
      genre: "Science Fiction",
      videoId: "V1mZ3vK9xQw",
    },
    {
      id: 12,
      name: "Interstellar",
      image: "https://m.media-amazon.com/images/I/61S2XaBPy6L._AC_UF894,1000_QL80_.jpg",
      description: "A crew ventures beyond our galaxy to find a new home as Earth dies, navigating wormholes and icy planets. Their journey tests love and science in a cosmic odyssey. A profound tale emerges. Director Christopher Nolan crafts this 2014 classic, with Matthew McConaughey and Anne Hathaway, blending realism and spectacle in a timeless space epic.",
      releaseDate: "2014-11-07",
      director: "Christopher Nolan",
      genre: "Science Fiction",
      videoId: "W2qZ5vJ8r3Y",
    },
    {
      id: 13,
      name: "The Matrix",
      image: "https://rukminim3.flixcart.com/image/850/1000/juk4gi80/poster/h/c/q/large-newposter8930-wall-poster-movies-the-matrix-poster-large-original-imaf5tgtzvb8pdpc.jpeg?q=20&crop=false",
      description: "Neo awakens to a simulated reality, joining Morpheus and Trinity to fight machines controlling humanity. His journey through code and combat tests reality and freedom. A revolutionary saga unfolds. Directors Lana and Lilly Wachowski craft this 1999 landmark, with Keanu Reeves and Laurence Fishburne, redefining sci-fi with groundbreaking action and philosophy.",
      releaseDate: "1999-03-31",
      director: "Lana Wachowski, Lilly Wachowski",
      genre: "Science Fiction",
      videoId: "X3mZ3vK9xQw",
    },
    {
      id: 14,
      name: "Monster Hunt 2",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00071452-jqkpgvfkjm-landscape.jpg",
      description: "Wuba, the monster prince, embarks on a perilous journey after parting from his human parents, Tian and Lan, as a sinister dark lord seeks to eliminate him. Befriending gambler Tu Sigu, Wuba navigates monster realms and human dangers, while Tian and Lan race to rescue him from a heavy bounty. Their quest tests courage and family bonds across vibrant landscapes. A whimsical odyssey unfolds. Directed by Raman Hui, this 2018 Chinese epic, with Tony Leung Chiu-wai and Bai Baihe, dazzles with stunning visuals and humor in a world where monsters and humans collide in a battle for peace.",
      releaseDate: "2018-02-16",
      director: "Raman Hui",
      genre: "Adventure",
      videoId: "P0mZ3vK9xQw",
    },
    {
      id: 15,
      name: "Arrival",
      image: "https://images6.alphacoders.com/112/1121126.jpg",
      description: "Linguist Louise Banks decodes an alien language to avert global conflict, journeying into their ships’ mysteries. Her quest tests communication and time in a cerebral odyssey. A profound tale emerges. Director Denis Villeneuve crafts this 2016 gem, with Amy Adams and Jeremy Renner, blending science and emotion in a first-contact masterpiece.",
      releaseDate: "2016-11-11",
      director: "Denis Villeneuve",
      genre: "Science Fiction",
      videoId: "Z5mZ3vK9xQw",
    },
    {
      id: 16,
      name: "Ex Machina",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/hd/004e5197949939.5ed0f9ac04c75.jpg",
      description: "Programmer Caleb tests AI Ava in a secluded retreat, uncovering her creator’s dark intentions. His journey into artificial consciousness tests ethics and desire. A tense odyssey unfolds. Director Alex Garland crafts this 2014 thriller, with Alicia Vikander and Domhnall Gleeson, exploring AI’s humanity in a sleek, suspenseful sci-fi narrative.",
      releaseDate: "2014-01-21",
      director: "Alex Garland",
      genre: "Science Fiction",
      videoId: "A6qZ5vJ8r3Y",
    },
    {
      id: 17,
      name: "Annihilation",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00062635-qqtcvsbbyw-landscape.jpg",
      description: "A biologist joins an expedition into a shimmering zone where nature mutates, seeking her lost husband. Her journey through alien landscapes tests sanity and survival. A surreal saga emerges. Director Alex Garland crafts this 2018 film, with Natalie Portman and Jennifer Jason Leigh, blending horror and sci-fi in a visually arresting exploration.",
      releaseDate: "2018-02-23",
      director: "Alex Garland",
      genre: "Science Fiction",
      videoId: "B7mZ3vK9xQw",
    },
    {
      id: 18,
      name: "Stranger Things Season 4",
      image: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/8a6a68144592045.628efcd3e77b5.jpg",
      description: "The Hawkins gang battles a supernatural threat from the Upside Down, with Eleven regaining her powers across dimensions. Their journey tests friendship amid horror. A thrilling odyssey emerges. The Duffer Brothers craft this 2022 Netflix hit, with Millie Bobby Brown and Finn Wolfhard, expanding the sci-fi saga with ’80s nostalgia and epic stakes.",
      releaseDate: "2022-05-27",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "C8qZ4vK9yTw",
    },
    {
      id: 19,
      name: "Severance Season 1",
      image: "https://resizing.flixster.com/_nZgYtA0npPZtBfx-Njc3y7YPOs=/fit-in/1152x864/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p21271543_b_h8_aa.jpg",
      description: "Mark Scout navigates a corporate world where memories split between work and life, uncovering a sinister plot. His journey through mind games tests identity and truth. A cerebral odyssey unfolds. Creator Ben Stiller crafts this 2022 Apple TV+ series, with Adam Scott and Zach Cherry, blending dystopian sci-fi with psychological depth.",
      releaseDate: "2022-02-18",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "D9mZ3vK9xQw",
    },
    {
      id: 20,
      name: "The Expanse Season 5",
      image: "https://static1.colliderimages.com/wordpress/wp-content/uploads/2021/11/the-expanse-s5-recap.jpg",
      description: "The crew of the *Rocinante* battles a protomolecule threat across the solar system, navigating political chaos. Their journey tests loyalty in a sprawling sci-fi epic. A galactic saga emerges. Directors [Various] craft this 2020 Amazon series, with Steven Strait and Dominique Tipper, delivering a gritty, space-faring adventure with rich world-building.",
      releaseDate: "2020-12-16",
      director: "[Various]",
      genre: "Science Fiction",
      videoId: "E0qZ5vJ8r3Y",
    },
  ];