export const topAnimeSeries = [
    {
      id: 1,
      name: "Solo Leveling Season 2",
      image: "https://4kwallpapers.com/images/wallpapers/solo-leveling-1920x1080-16126.jpg",
      description: "Jin-Woo Sung, once the weakest Hunter, unleashes his newfound leveling powers to confront alien invaders, unraveling a dark mystery in a portal-ravaged world. His ascent tests strength and resolve in a perilous odyssey. A gripping saga unfolds. Directed by Shunsuke Nakashige, this 2025 Crunchyroll sequel, with Taito Ban, builds on the 2024 hit with stunning fights and deeper stakes from Chugong’s manhwa.",
      releaseDate: "2025-01-04",
      director: "Shunsuke Nakashige",
      genre: "Drama",
      videoId: "Q1mZ3vK9xQw",
    },
    {
        id: 6,
        name: "Naruto",
        image: "https://wallpapercave.com/wp/wp8840620.jpg",
        description: "Naruto Uzumaki, a ninja with a fox spirit, trains to become Hokage, facing foes and friends in a war-torn village. His dream tests perseverance in an epic odyssey. A legendary saga emerges. Directed by Hayato Date, this 2002–2007 TV Tokyo classic, with Junko Takeuchi, shaped shonen with its emotional depth.",
        releaseDate: "2002-10-03",
        director: "Hayato Date",
        genre: "Drama",
        videoId: "V6qZ4vK9yTw",
      },
      {
        id: 7,
        name: "Hunter x Hunter",
        image: "https://images.alphacoders.com/560/560960.png",
        description: "Gon Freecss seeks his father, mastering Nen through deadly trials and the Chimera Ant arc. His quest tests courage in a dark odyssey. A thrilling saga unfolds. Directed by Hiroshi Kōjina, this 2011–2014 Fuji TV series, with Megumi Han, adapts Yoshihiro Togashi’s manga with strategic brilliance.",
        releaseDate: "2011-10-02",
        director: "Hiroshi Kōjina",
        genre: "Drama",
        videoId: "W7mZ3vK9xQw",
      },
      {
        id: 63,
        name: "Jujutsu Kaisen Season 1",
        image: "https://fandomwire.com/wp-content/uploads/2023/11/jujustu-kaigen.jpg",
        description: "Yuji Itadori, a high schooler, swallows a cursed object to save friends, joining jujutsu sorcerers to combat malevolent curses, including the deadly Sukuna. His journey tests courage and sacrifice in a dark odyssey. A gripping saga unfolds. Directed by Park Sunghoo, this 2020–2021 MAPPA series, with Junya Enoki, adapts Gege Akutami’s manga with stunning animation and emotional stakes, setting the stage for battles against cursed spirits in a supernatural world.",
        releaseDate: "2020-10-03",
        director: "Park Sunghoo",
        genre: "Drama",
        videoId: "Q2mZ3vK9xQw",
      },
      {
        id: 8,
        name: "One Piece",
        image: "https://static1.cbrimages.com/wordpress/wp-content/uploads/2024/01/split-images-of-luffy.jpg?q=70&fit=contain&w=1200&h=628&dpr=1",
        description: "Monkey D. Luffy sails with the Straw Hats to find the One Piece, battling pirates and governments across seas. His freedom quest tests friendship in a grand odyssey. An epic saga emerges. Directed by Konosuke Uda and others, this 1999–present Fuji TV series, with Mayumi Tanaka, adapts Eiichiro Oda’s manga.",
        releaseDate: "1999-10-20",
        director: "Konosuke Uda, [Various]",
        genre: "Drama",
        videoId: "X8qZ5vJ8r3Y",
      },
      {
        id: 9,
        name: "Bleach",
        image: "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2022/09/Bleach-Thousand-Year-Blood-War-Feature.jpg",
        description: "Ichigo Kurosaki, a teen soul reaper, protects the living from Hollows, facing the Soul Society’s secrets. His duty tests resolve in a spiritual odyssey. A powerful saga unfolds. Directed by Noriyuki Abe, this 2004–2012 TV Tokyo series, with Masakazu Morita, adapts Tite Kubo’s manga with action-packed arcs.",
        releaseDate: "2004-10-05",
        director: "Noriyuki Abe",
        genre: "Drama",
        videoId: "Y9mZ3vK9xQw",
      },
      {
        id: 10,
        name: "Fullmetal Alchemist: Brotherhood",
        image: "https://m.media-amazon.com/images/S/pv-target-images/56610e560ff3e0f94ebc2237d6e76d583d06e33a5e5c01b75d405a18c1d22d90.jpg",
        description: "Edward and Alphonse Elric seek the Philosopher’s Stone to restore their bodies, facing alchemical conspiracies. Their quest tests sacrifice in a profound odyssey. A moving saga emerges. Directed by Yasuhiro Irie, this 2009–2010 MBS series, with Romi Park, adapts Hiromu Arakawa’s manga with unmatched storytelling.",
        releaseDate: "2009-04-05",
        director: "Yasuhiro Irie",
        genre: "Drama",
        videoId: "Z0qZ4vK9yTw",
      },
      {
        id: 11,
        name: "One Punch Man",
        image: "https://cdn11.bigcommerce.com/s-nq6l4syi/images/stencil/1280x1280/products/158816/506804/209092-1024__43158.1664275699.jpg?c=2",
        description: "Saitama, a hero who defeats foes with one punch, seeks a worthy challenge amid monster attacks. His journey tests purpose in a humorous odyssey. A dynamic saga unfolds. Directed by Shingo Natsume, this 2015–2019 series, with Makoto Furukawa, adapts ONE’s webcomic with epic fights.",
        releaseDate: "2015-10-05",
        director: "Shingo Natsume",
        genre: "Drama",
        videoId: "A1mZ3vK9xQw",
      },
      {
        id: 13,
        name: "My Hero Academia Season 7",
        image: "https://wallpapercg.com/media/ts_orig/27232.webp",
        description: "Deku and Class 1-A battle All For One’s forces, pushing their quirks to the limit in a war-torn world. Their heroism tests sacrifice in a fierce odyssey. An epic saga unfolds. Directed by Kenji Nagasaki, this 2024 Crunchyroll series, with Daiki Yamashita, adapts Kohei Horikoshi’s manga finale.",
        releaseDate: "2024-05-04",
        director: "Kenji Nagasaki",
        genre: "Drama",
        videoId: "C3mZ3vK9xQw",
      },
      {
        id: 14,
        name: "Demon Slayer: Hashira Training Arc",
        image: "https://arynews.tv/wp-content/uploads/2025/02/Demon-Slayer.jpg",
        description: "Tanjiro trains with the Hashira to face Muzan, bonding with allies amid intense drills in a demon-threatened world. His growth tests resolve in a fierce odyssey. A powerful saga unfolds. Directed by Haruo Sotozaki, this 2024 Crunchyroll hit, with Natsuki Hanae, continues Koyoharu Gotouge’s epic.",
        releaseDate: "2024-05-12",
        director: "Haruo Sotozaki",
        genre: "Drama",
        videoId: "D4qZ4vK9yTw",
      },
      {
        id: 12,
        name: "Attack on Titan",
        image: "https://www.abystyle.com/img/c/m/338_S_Attack_On_Titan.jpg",
        description: "Eren Yeager battles Titans to reclaim humanity’s freedom, uncovering a brutal truth about his world. His fight tests vengeance in a harrowing odyssey. A monumental saga emerges. Directed by Tetsuro Araki, this 2013–2023 series, with Yuki Kaji, adapts Hajime Isayama’s manga with intense drama.",
        releaseDate: "2013-04-07",
        director: "Tetsuro Araki",
        genre: "Drama",
        videoId: "B2qZ5vJ8r3Y",
      },
      {
        id: 13,
        name: "Death Note",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR123789dzk1MB-bqrwXFLiV1aX5FY-OMARIg&s",
        description: "Light Yagami uses a death note to purge crime, hunted by detective L in a deadly mind game. His ambition tests morality in a dark odyssey. A psychological saga unfolds. Directed by Tetsuro Araki, this 2006–2007 NTV series, with Mamoru Miyano, adapts Tsugumi Ohba’s manga.",
        releaseDate: "2006-10-04",
        director: "Tetsuro Araki",
        genre: "Drama",
        videoId: "C3mZ3vK9xQw",
      },
    
    
    {
      id: 5,
      name: "Sakamoto Days",
      image: "https://images3.alphacoders.com/134/1349910.png",
      description: "Taro Sakamoto, a retired hitman turned family man, defends his quiet life from assassins with deadly skill. His journey tests loyalty amid action in a thrilling odyssey. A bold saga unfolds. Directed by Masaki Watanabe, this 2025 TBD series, adapting Yuto Suzuki’s manga, promises humor and combat for January 2025 release.",
      releaseDate: "2025-01-01",
      director: "Masaki Watanabe",
      genre: "Drama",
      videoId: "U5mZ3vK9xQw",
    },
    {
      id: 6,
      name: "Blue Lock",
      image: "https://4kwallpapers.com/images/wallpapers/blue-lock-poster-3840x2160-20014.jpg",
      description: "Isagi Yoichi trains in a ruthless program to become Japan’s top striker, facing rivals in intense soccer matches. His ambition tests skill in a competitive odyssey. A dynamic saga emerges. Directed by Tetsuaki Watanabe, this 2024–2025 series, with Kazuki Ura, adapts Muneyuki Kaneshiro’s manga with Olympic-fueled hype.",
      releaseDate: "2024-10-05",
      director: "Tetsuaki Watanabe",
      genre: "Drama",
      videoId: "V6qZ4vK9yTw",
    },
 
  {
        id: 72,
        name: "Wind Breaker Season 1",
        image: "https://4kwallpapers.com/images/wallpapers/wind-breaker-5k-3840x2160-18815.jpg",
        description: "Haruka Sakura, a loner seeking to be the strongest, joins Furin High, a school of brawlers who protect their town as the Bofurin gang. Facing rival Shishitoren, his quest tests strength and belonging in a gritty odyssey. A dynamic saga unfolds. Directed by Toshifumi Akai, this 2024 CloverWorks series, with Yuma Uchida, adapts Satoru Nii’s manga with stunning fight choreography and emotional growth, ending on a cliffhanger with the KEEL gang’s rise, setting up Season 2 for April 2025.",
        releaseDate: "2024-04-05",
        director: "Toshifumi Akai",
        genre: "Drama",
        videoId: "Z2mZ3vK9xQw",
      },


  ];