export const adventureMovies = [
    
        {
          id: 1,
          name: "Inception",
          image: "https://images7.alphacoders.com/518/518783.jpg",
          description: "Dom Cobb, a skilled thief, infiltrates dreams to steal secrets for corporate espionage. Offered a chance to reclaim his life by planting an idea in a billionaire’s mind, he leads a team into layered dream worlds where reality blurs. Facing armed projections and subconscious defenses, Cobb battles guilt over his lost wife as the mission teeters on collapse. Christopher Nolan crafts a mind-bending adventure of deception and identity, with Leonardo DiCaprio’s haunted lead driving this Oscar-winning sci-fi epic that redefines cinematic storytelling.",
          releaseDate: "2010-07-16",
          director: "Christopher Nolan",
          genre: "Adventure",
          videoId: "I9qZ5vJ8r3Y",
        },
        {
          id: 2,
          name: "Interstellar",
          image: "https://m.media-amazon.com/images/I/61S2XaBPy6L._AC_UF894,1000_QL80_.jpg",
          description: "In a dying Earth, ex-astronaut Cooper leads a desperate mission through a wormhole to find a new home for humanity. Navigating uncharted planets with his crew, he confronts black holes, time dilation, and the sacrifices of love. Guided by cryptic messages from his daughter, Cooper’s journey tests human resilience against cosmic odds. Christopher Nolan’s visionary tale blends science and emotion, with Matthew McConaughey’s heartfelt performance anchoring this space odyssey, exploring survival and legacy in a breathtaking adventure.",
          releaseDate: "2014-11-07",
          director: "Christopher Nolan",
          genre: "Adventure",
          videoId: "J7mZ3vK9xQw",
        },
        {
          id: 3,
          name: "The Lord of the Rings: The Fellowship of the Ring",
          image: "https://dyn1.heritagestatic.com/lf?set=path%5B1%2F1%2F4%2F5%2F1%2F11451494%5D&call=url%5Bfile%3Aproduct.chain%5D",
          description: "In Middle-earth, hobbit Frodo Baggins inherits a Ring of power that could doom the world if wielded by the Dark Lord Sauron. Joining a diverse fellowship—Aragorn, Gandalf, and others—Frodo embarks on a perilous quest to destroy it in Mount Doom. Facing orcs, trolls, and inner doubts, their journey through stunning landscapes tests courage and unity. Peter Jackson’s epic adaptation of Tolkien’s saga, with Elijah Wood’s earnest Frodo, launches a legendary adventure of friendship and sacrifice that reshaped fantasy cinema.",
          releaseDate: "2001-12-19",
          director: "Peter Jackson",
          genre: "Adventure",
          videoId: "K5vJ9kZbX8Z",
        },
        {
          id: 4,
          name: "Dune: Part Two",
          image: "https://i.ytimg.com/vi/53BBRKF-L60/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGH8gQygTMA8=&rs=AOn4CLDgS78KBd_b20u0o-YBvLDGs6De2A",
          description: "Paul Atreides, heir to a noble house, rises among the Fremen of Arrakis after his family’s betrayal. Mastering the desert’s ways and a messianic prophecy, he leads a revolt against the tyrannical Harkonnens to control the spice trade. With Chani by his side, Paul’s visions of war clash with his desire for peace in epic battles across dunes. Denis Villeneuve’s stunning sequel, starring Timothée Chalamet, expands Herbert’s saga into a sweeping adventure of power, destiny, and ecological struggle.",
          releaseDate: "2024-03-01",
          director: "Denis Villeneuve",
          genre: "Adventure",
          videoId: "L8mZ3vK9yTw",
        },
        {
          id: 5,
          name: "The Lion King",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsdpWDh0aHIl_QtUjbZ_UC71BBJo6RK2G33g&s",
          description: "Simba, a young lion cub, flees his pride after his father Mufasa’s murder by his uncle Scar, who usurps the throne. Guided by friends Timon and Pumbaa, Simba grows in exile, wrestling with guilt and destiny. Returning to reclaim Pride Rock, he battles Scar in a dramatic showdown to restore balance. Jon Favreau’s photorealistic remake of Disney’s classic, with James Earl Jones and Beyoncé, delivers a heartfelt adventure of courage, family, and redemption in the African savanna.",
          releaseDate: "2019-07-19",
          director: "Jon Favreau",
          genre: "Adventure",
          videoId: "M7qZ4vK9xRt",
        },
        {
          id: 6,
          name: "Moana",
          image: "https://coldspringharbor.librarycalendar.com/sites/default/files/2022-07/Moana-Movie-Poster-landscape-1024x461.jpg",
          description: "Moana, a Polynesian teen, defies her village’s boundaries to save her people from a blight, guided by the ocean’s call. Teaming with demigod Maui, she sails treacherous seas, facing monsters like Te Kā to return a stolen heart to Te Fiti. Her journey uncovers her heritage and courage in vibrant, wave-tossed adventures. Directors Ron Clements and John Musker craft Disney’s animated triumph, with Auliʻi Cravalho’s spirited voice, celebrating exploration, identity, and resilience across the Pacific.",
          releaseDate: "2016-11-23",
          director: "Ron Clements, John Musker",
          genre: "Adventure",
          videoId: "N9qZ5vJ8r3Y",
        },
        {
          id: 7,
          name: "Sonic the Hedgehog: The Movie",
          image: "https://i.pinimg.com/736x/f4/32/df/f432dfa719ecd48214de35238cce27ae.jpg",
          description: "Sonic, a speedy hedgehog, teams with human Tom Wachowski to stop Dr. Robotnik’s plot to harness his power and dominate Earth. Racing through cities and forests, they face robotic armies and Robotnik’s cunning traps in a high-energy chase. Sonic’s quest for belonging fuels their unlikely alliance in a battle for freedom. Directors Jeff Fowler and Tim Miller bring Sega’s icon to life, with Ben Schwartz’s witty voice, delivering a family-friendly adventure packed with humor and supersonic thrills.",
          releaseDate: "2020-02-14",
          director: "Jeff Fowler",
          genre: "Adventure",
          videoId: "O8mZ3vK9xQw",
        },
        {
          id: 8,
          name: "Jurassic World Dominion",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkh_J3iw7J8pMWu2hW74SptFfUCbksYaQCvw&s",
          description: "Dinosaurs roam a world shared with humans after Jurassic World’s collapse, sparking a global crisis. Owen Grady and Claire Dearing race to rescue Maisie Lockwood from a biotech firm exploiting dinosaurs, facing raptors and a giant locust plague. Their journey across continents pits survival against greed in epic chases and prehistoric battles. Director Colin Trevorrow concludes the saga with Chris Pratt and Bryce Dallas Howard, blending awe and danger in a thrilling adventure that redefines humanity’s place with nature.",
          releaseDate: "2022-06-10",
          director: "Colin Trevorrow",
          genre: "Adventure",
          videoId: "P7qZ4vK9yTw",
        },
        {
          id: 9,
          name: "Azaad",
          image: "https://i0.wp.com/www.socialnews.xyz/wp-content/uploads/2025/01/13/ghkrmiqboaa5uwk1964711.jpg?w=777&crop=0,10,777px,437px",
          description: "In this 1955 Indian classic, Azaad, a noble bandit, roams the deserts of Rajasthan, aiding the oppressed while evading British rule. Disguised as a prince, he rescues Shobha from a forced marriage, sparking a daring chase across rugged terrains. His loyalty and courage shine as he battles corrupt officials and rival gangs, seeking justice for the downtrodden. Director S.M. Sriramulu Naidu crafts a swashbuckling tale of honor, with Dilip Kumar’s charismatic performance driving this timeless adventure of rebellion and romance in a vibrant, lawless land.",
          releaseDate: "1955-01-07",
          director: "S.M. Sriramulu Naidu",
          genre: "Adventure",
          videoId: "Q9qZ5vJ8r3Y",
        },
        {
          id: 10,
          name: "Alpha",
          image: "https://lh5.googleusercontent.com/proxy/GTmaRaJ1QV6wE6BpMsYpqmyfyIFEtbpcLFKvp1rmky7bgEV5PQsx98sUOsccoJ9EkvhH1C7XBG9bZGqGbA5PrnevEOhBvWkXRd2m",
          description: "In the Ice Age, Keda, a young hunter, is left for dead after a bison hunt gone wrong, stranded in a harsh prehistoric wilderness. Facing starvation and predators, he forms a bond with a wounded wolf, Alpha, forging a partnership to survive. Their journey across treacherous landscapes tests courage and trust, leading to a triumphant return. Director Albert Hughes delivers a visceral survival epic, with Kodi Smit-McPhee’s raw portrayal illuminating this primal adventure of man and nature’s uneasy alliance.",
          releaseDate: "2018-08-17",
          director: "Albert Hughes",
          genre: "Adventure",
          videoId: "R7mZ3vK9xQw",
        },
        {
          id: 11,
          name: "Ne Zha",
          image: "https://i.ytimg.com/vi/wnNOJeAYuBE/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBoKwf2N3MNinM4S0xC2QcJTDNI6g",
          description: "Born from a heavenly pearl as a demon child, Ne Zha faces a prophecy foretelling his world’s destruction. Outcast and feared in Chentang Pass, he battles his demonic nature under the guidance of Taoist master Taiyi Zhenren. When rival Ao Bing, born of a spirit pearl, becomes his foe, Ne Zha’s journey tests his choice between good and evil. With stunning animation and emotional depth, director Jiaozi reimagines the Chinese myth from *Investiture of the Gods*, with Lü Yanting’s spirited voice leading this epic adventure of fate, sacrifice, and redemption.",
          releaseDate: "2019-07-13",
          director: "Jiaozi",
          genre: "Adventure",
          videoId: "H9qZ5vJ8r3Y",
        },
        {
          id: 12,
          name: "Jurassic World",
          image: "https://imageio.forbes.com/blogs-images/scottmendelson/files/2018/06/jurassic-world-2B-1200x594.jpg?format=jpg&height=600&width=1200&fit=bounds",
          description: "On Isla Nublar, Jurassic World’s genetically engineered dinosaurs, including the Indominus rex, break free, threatening tourists and staff. Owen Grady, a raptor trainer, teams with Claire Dearing to contain the chaos, racing through jungles and labs to save lives. Their mission uncovers corporate greed behind the park’s downfall. Director Colin Trevorrow crafts a thrilling revival of the franchise, with Chris Pratt and Bryce Dallas Howard leading this prehistoric adventure of survival, wonder, and the perils of playing god with nature.",
          releaseDate: "2015-06-12",
          director: "Colin Trevorrow",
          genre: "Adventure",
          videoId: "T7qZ4vK9xRt",
        },
        {
          id: 13,
          name: "Life of Pi",
          image: "https://c4.wallpaperflare.com/wallpaper/672/360/13/5bd4a9d93f219-wallpaper-preview.jpg",
          description: "Pi Patel, a young Indian boy, survives a shipwreck, adrift on a lifeboat with a Bengal tiger, Richard Parker, in the Pacific Ocean. Facing storms, starvation, and the tiger’s threat, Pi’s journey becomes a test of faith and resilience across endless waters. Through vivid hallucinations and survival tactics, he finds meaning in the wild. Director Ang Lee adapts Yann Martel’s novel into a mesmerizing adventure, with Suraj Sharma’s soulful performance illuminating this tale of hope and human-animal connection.",
          releaseDate: "2012-11-21",
          director: "Ang Lee",
          genre: "Adventure",
          videoId: "U9qZ5vJ8r3Y",
        },
        {
          id: 14,
          name: "The Great Wall",
          image: "https://guysgurugrades.wordpress.com/wp-content/uploads/2017/02/the-great-wall-poster.jpg",
          description: "In 11th-century China, mercenary William Garin joins the Nameless Order defending the Great Wall from monstrous Tao Tei invaders. Captured with Pero Tovar, he fights alongside General Lin Mae in epic battles, using innovative tactics to protect the empire. Their quest uncovers ancient secrets amid the wall’s grandeur. Director Zhang Yimou blends historical spectacle with fantasy, starring Matt Damon in a visually stunning adventure of courage, cultural clash, and humanity’s stand against otherworldly forces.",
          releaseDate: "2016-12-16",
          director: "Zhang Yimou",
          genre: "Adventure",
          videoId: "V8mZ3vK9xQw",
        },
        {
          id: 15,
          name: "Spectral",
          image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00036170-bwlxaufzhr-landscape.jpg",
          description: "In a war-torn Moldova, DARPA scientist Mark Clyne investigates ghostly specters decimating U.S. troops. Teaming with a special forces unit, he uncovers a Soviet experiment gone awry, leading to intense combat in a spectral-infested city. Their mission to neutralize the threat blends technology with bravery across ruined streets. Director Nic Mathieu crafts a tense, sci-fi adventure, with James Badge Dale’s determined lead driving this military thriller into uncharted supernatural territory.",
          releaseDate: "2016-12-09",
          director: "Nic Mathieu",
          genre: "Adventure",
          videoId: "W7qZ4vK9yTw",
        },
        {
          id: 16,
          name: "Warcraft",
          image: "https://m.media-amazon.com/images/M/MV5BMTY2NzQ1NTg1NV5BMl5BanBnXkFtZTgwNjE2MzA3ODE@._V1_.jpg",
          description: "When the orcish Horde invades Azeroth through a portal, human guardian Anduin Lothar and mage Khadgar ally with orc defector Durotan to prevent war. Battles rage across mystical lands, blending magic and might as both sides seek survival. Their uneasy truce tests loyalty in a clash of worlds. Director Duncan Jones adapts Blizzard’s game into a sweeping adventure, with Travis Fimmel and Toby Kebbell leading this epic tale of honor and conflict in a fantasy realm.",
          releaseDate: "2016-06-10",
          director: "Duncan Jones",
          genre: "Adventure",
          videoId: "X9qZ5vJ8r3Y",
        },
        {
          id: 17,
          name: "Man of Steel",
          image: "https://c4.wallpaperflare.com/wallpaper/438/958/473/2013-man-of-steel-hd-man-of-steel-poster-wallpaper-preview.jpg",
          description: "Kal-El, raised as Clark Kent on Earth, discovers his Kryptonian heritage as a planet-destroying threat looms. Battling General Zod, he harnesses superhuman strength and flight to protect humanity, grappling with his dual identity. His journey across cities and skies defines a hero’s rise. Director Zack Snyder reimagines Superman’s origin, with Henry Cavill’s powerful portrayal anchoring this action-packed adventure of destiny, sacrifice, and the birth of a modern icon.",
          releaseDate: "2013-06-14",
          director: "Zack Snyder",
          genre: "Adventure",
          videoId: "Y8mZ3vK9xQw",
        },
        {
          id: 18,
          name: "The Revenant",
          image: "https://paulist.org/app/uploads/2016/02/Revenant.jpg",
          description: "Hugh Glass, a frontiersman, is mauled by a bear and left for dead by his 1820s fur-trapping crew in the unforgiving American wilderness. Driven by vengeance against the traitor John Fitzgerald, Glass crawls through snow and rivers, enduring frostbite and starvation. His solitary quest for justice transforms into a test of survival and spirit. Director Alejandro G. Iñárritu crafts a visceral epic, with Leonardo DiCaprio’s grueling performance earning an Oscar, blending raw nature with a tale of human resilience and retribution.",
          releaseDate: "2015-12-25",
          director: "Alejandro G. Iñárritu",
          genre: "Adventure",
          videoId: "Z9qZ5vJ8r3Y",
        },
        {
          id: 19,
          name: "Mad Max: Fury Road",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO4Rn25dl7FyN2C0Ou7a7VE4WKo58Vp8w2eg&s",
          description: "In a post-apocalyptic wasteland, Max Rockatansky teams with Imperator Furiosa to escape a tyrannical warlord, Immortan Joe, who enslaves women for breeding. Their high-octane chase across deserts in a war rig faces sandstorms and relentless pursuers, fueled by a fight for freedom. The duo’s rebellion ignites a stunning spectacle of vehicular combat and survival. Director George Miller delivers a relentless, visually arresting adventure, with Tom Hardy and Charlize Theron leading this modern classic of action and redemption.",
          releaseDate: "2015-05-15",
          director: "George Miller",
          genre: "Adventure",
          videoId: "A8mZ3vK9xQw",
        },
        {
          id: 20,
          name: "The Martian",
          image: "https://mir-s3-cdn-cf.behance.net/projects/404/d06db0120605581.Y3JvcCw4NDIsNjU4LDAsMA.jpg",
          description: "Astronaut Mark Watney is stranded on Mars after a storm forces his crew to abandon him, presumed dead. Using science and ingenuity, he cultivates potatoes and signals NASA for rescue, battling isolation and resource scarcity. His survival odyssey inspires a global effort to bring him home across the red planet’s harsh terrain. Director Ridley Scott crafts a gripping space adventure, with Matt Damon’s witty resilience anchoring this tale of human perseverance and the triumph of intellect over adversity.",
          releaseDate: "2015-10-02",
          director: "Ridley Scott",
          genre: "Adventure",
          videoId: "B7qZ4vK9yTw",
        },
        {
          id: 21,
          name: "Pirates of the Caribbean: The Curse of the Black Pearl",
          image: "https://images.squarespace-cdn.com/content/v1/5b18735a3917ee20d18a2117/f96bf719-5573-4c0b-85ac-a40495028dc6/scale.jpg",
          description: "Captain Jack Sparrow seeks to reclaim his ship, the Black Pearl, hijacked by mutineer Barbossa, whose cursed crew turns skeletal under moonlight. Teaming with Will Turner and Elizabeth Swann, Jack navigates treacherous seas, battling undead pirates for a cursed Aztec gold. Their swashbuckling quest blends humor and danger across Caribbean waters. Director Gore Verbinski launches a franchise with Johnny Depp’s iconic Sparrow leading this rollicking adventure of greed, loyalty, and supernatural intrigue.",
          releaseDate: "2003-07-09",
          director: "Gore Verbinski",
          genre: "Adventure",
          videoId: "C9qZ5vJ8r3Y",
        },
        {
          id: 22,
          name: "Avatar",
          image: "https://c4.wallpaperflare.com/wallpaper/810/33/235/movies-avatar-1680x1050-entertainment-movies-hd-art-wallpaper-preview.jpg",
          description: "Jake Sully, a paraplegic Marine, inhabits a Na’vi avatar on Pandora, a lush alien moon, to infiltrate its indigenous people for Earth’s resources. Falling for Neytiri, he joins the Na’vi against human colonizers, leading a rebellion in epic aerial battles. His journey transforms from espionage to defending a world of wonder. Director James Cameron revolutionizes cinema with this groundbreaking adventure, starring Sam Worthington, blending spectacle and environmental themes in a Pandora-spanning saga.",
          releaseDate: "2009-12-18",
          director: "James Cameron",
          genre: "Adventure",
          videoId: "D8mZ3vK9xQw",
        },
        {
          id: 23,
          name: "The Hobbit: An Unexpected Journey",
          image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9tnxOrsiru4_hiSOJ6QBq5y49OsZ57zf7tw&s",
          description: "Bilbo Baggins, a timid hobbit, joins Gandalf and a band of dwarves, led by Thorin Oakenshield, to reclaim Erebor from the dragon Smaug. Their perilous trek through Middle-earth faces trolls, goblins, and a riddle game with Gollum, testing Bilbo’s courage. The discovery of a Ring sets a grander fate in motion. Director Peter Jackson adapts Tolkien’s prelude with Martin Freeman’s endearing Bilbo, launching a sweeping adventure of bravery and destiny in a richly imagined realm.",
          releaseDate: "2012-12-14",
          director: "Peter Jackson",
          genre: "Adventure",
          videoId: "E7qZ4vK9yTw",
        },
        {
          id: 24,
          name: "Journey to the West: The Demons Strike Back",
          image: "https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2F4%2Fgracenote%2F407e98e253dfc6d1716c0e4b5a67becf.jpg",
          description: "Tang Sanzang and his disciples—Sun Wukong, Zhu Bajie, and Sha Wujing—continue their perilous quest to the West for Buddhist scriptures, facing new demonic threats. Amidst tensions with Wukong, blamed for a past loss, they battle spider demons, Red Boy, and the White Bone Spirit in a land of chaos. Their journey tests forgiveness and unity, culminating in a desert trek toward enlightenment. Directed by Tsui Hark with Stephen Chow’s influence, this sequel blends slapstick humor with dazzling action, starring Kris Wu and Lin Gengxin, delivering a whimsical yet epic conclusion to their saga.",
          releaseDate: "2017-01-28",
          director: "Tsui Hark",
          genre: "Adventure",
          videoId: "I8mZ3vK9xQw",
        },
        {
          id: 25,
          name: "Jumanji: Welcome to the Jungle",
          image: "https://rukminim2.flixcart.com/image/850/1000/jnc2bgw0/poster/q/k/j/medium-hollywood-movie-wall-poster-jumanji-welcome-to-the-jungle-original-imafayzgbdutkykt.jpeg?q=20&crop=false",
          description: "Four teens are sucked into a video game, transforming into adult avatars—Spencer as a brawny explorer, Martha as a martial artist—trapped in Jumanji’s jungle. Facing rhinos, a vengeful hunter, and puzzles, they must complete the game to escape. Their teamwork evolves from rivalry to camaraderie in a wild, danger-filled quest. Directors Jake Kasdan and Chris McKenna revive the franchise with Dwayne Johnson and Kevin Hart, delivering a hilarious, action-packed adventure of self-discovery and survival.",
          releaseDate: "2017-12-20",
          director: "Jake Kasdan",
          genre: "Adventure",
          videoId: "G8mZ3vK9xQw",
        },
  ];
