export const trendingmovies = [
  
    {
        id: 1,
        name: "Chhaava",
        image: "https://images.filmibeat.com/ph-big/img_og/chhavva-movie-stils-on-set-pictures-poster-stills1724226886.jpg",
        description: "After Chhatrapati Shivaji Maharaj’s death in 1680, his son Sambhaji Maharaj, portrayed by Vicky Kaushal, rises to defend the Maratha Empire against Mughal emperor Aurangzeb, played by Akshaye Khanna. Facing betrayal and fierce battles, Sambhaji’s journey across Deccan forts tests his courage and leadership, seeking to honor his father’s legacy. A tale of valor unfolds amidst political intrigue. Directed by Laxman Utekar, this 2025 epic, with Rashmika Mandanna as Yesubai, blends stunning visuals and A.R. Rahman’s score, capturing Sambhaji’s defiant odyssey against overwhelming odds in a richly crafted historical landscape.",
        releaseDate: "2025-02-14",
        director: "Laxman Utekar",
        genre: "Adventure",
        videoId: "I2mZ3vK9xQw",
      },
      {
        id: 3,
        name: "Solo Leveling Season 2",
        image: "https://4kwallpapers.com/images/wallpapers/solo-leveling-5120x2880-19518.png",
        description: "Sung Jinwoo, now a powerful Shadow Monarch, confronts the aftermath of the Jeju Island arc, facing new threats like the Monarchs of Fangs and Frost. His journey through dungeons and battles tests his growing strength and leadership, unraveling mysteries of his leveling system. A tale of ascension unfolds. Directed by Shunsuke Nakashige, this 2025 Crunchyroll hit, with Taito Ban voicing Jinwoo, builds on the Red Gate arc’s intensity, captivating fans with epic fights and a world-expanding odyssey of power and destiny.",
        releaseDate: "2025-01-04",
        director: "Shunsuke Nakashige",
        genre: "Adventure",
        videoId: "F1mZ3vK9xQw",
      },
      {
        id: 4,
        name: "Squid Game Season 2",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUVlbDLE1SLSehl8jEhRi4-lZFF8DQEEIIKA&s",
        description: "Seong Gi-hun returns to the deadly games, seeking revenge against the Front Man, navigating new challenges with higher stakes and unexpected allies. His journey through treacherous rounds tests survival and morality in a brutal arena. A gripping saga emerges. Directed by Hwang Dong-hyuk, this 2025 Netflix finale, starring Lee Jung-jae and Lee Byung-hun, builds on Season 1’s tension, delivering a climactic adventure of human resilience and sacrifice, set to conclude on June 27.",
        releaseDate: "2025-01-01",
        director: "Hwang Dong-hyuk",
        genre: "Adventure",
        videoId: "G7qZ4vK9yTw",
      },
    {
      id: 5,
      name: "Game Changer",
      image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00311772-besdebnnvv-landscape.jpg",
      description: "An idealistic IAS officer battles corruption in a high-stakes political thriller, racing across urban and rural India to reform a tainted system. Facing assassins and betrayal, his journey tests integrity and courage. A tale of justice unfolds. Director Shankar directs Ram Charan in this 2025 Telugu action epic, blending political intrigue with explosive action, captivating audiences with a quest for change in a divided land.",
      releaseDate: "2025-01-10",
      director: "Shankar",
      genre: "Adventure",
      videoId: "X8mZ3vK9xQw",
    },
    {
        id: 6,
        name: "War for the Planet of the Apes",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvKSA9ut57bt4AJjv_P32_8ZTmCwpXSw1pHQ&s",
        description: "After suffering devastating losses, Caesar, the intelligent ape leader, embarks on a mythic quest for vengeance against the ruthless Colonel McCullough and his human army, Alpha-Omega. Leading his tribe through snowy wilderness and human captivity, Caesar wrestles with his darker instincts, seeking a new home amid a brutal war. A tale of survival and sacrifice unfolds. Directed by Matt Reeves, this 2017 epic, with Andy Serkis’ motion-captured Caesar and Woody Harrelson’s chilling Colonel, blends stunning visuals and Michael Giacchino’s score, delivering a poignant adventure that concludes the trilogy with a battle for Earth’s future.",
        releaseDate: "2017-07-14",
        director: "Matt Reeves",
        genre: "Adventure",
        videoId: "J3mZ3vK9xQw",
      },
    {
      id: 7,
      name: "My Fault: London",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbeezovuhyJlIIe7WMhoYiYXPWAdzszxOsKg&s",
      description: "Noah and Nick’s passionate romance faces new trials in London, where family secrets and rivalries ignite a dangerous chase across the city’s underworld. Their love-driven journey tests loyalty amid betrayal. A steamy saga unfolds. Director [Unknown] expands the Spanish franchise in 2025, with Nicole Wallace and Gabriel Guevara leading this emotional adventure, blending romance and suspense in a bustling urban landscape.",
      releaseDate: "2025-07-18",
      director: "[Unknown]",
      genre: "Adventure",
      videoId: "Z9qZ5vJ8r3Y",
    },
    {
      id: 8,
      name: "I Am Kathalan",
      image: "https://static.moviecrow.com/marquee/i-am-kathalan-review---an-interesting-technology-based-thriller/237504_thumb_665.jpg",
      description: "A young man’s quest for justice turns perilous as he infiltrates a criminal network, navigating Kerala’s shadows to expose corruption. His journey blends bravery with danger across urban and rural terrains. A tale of defiance emerges. Director [Unknown] stars Naslen K. Gafoor in this 2025 Malayalam thriller, delivering a gripping adventure of identity and retribution in a world of deceit.",
      releaseDate: "2025-03-14",
      director: "[Unknown]",
      genre: "Adventure",
      videoId: "A1mZ3vK9xQw",
    },
    {
      id: 9,
      name: "Twilight of the Warriors: Walled In",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr7RuP8CYj4yLv84C2beLGpxHyrGvzGvU_2Q&s",
      description: "In 1980s Kowloon Walled City, Chan Lok-kwun fights to survive gang wars and protect his found family, navigating a labyrinth of alleys and danger. His journey tests loyalty in a lawless urban jungle. An epic unfolds. Director Soi Cheang crafts a 2025 Hong Kong action-adventure, with Raymond Lam leading this visceral tale of brotherhood and survival in a crumbling fortress.",
      releaseDate: "2025-05-01",
      director: "Soi Cheang",
      genre: "Adventure",
      videoId: "B7qZ4vK9yTw",
    },
    {
        id: 10,
        name: "Hyper Knife",
        image: "https://img10.hotstar.com/image/upload/f_auto/sources/r1/cms/prod/2542/1732003122542-i",
        description: "Dr. Jung Se-ok, a disgraced neurosurgeon haunted by a past tragedy, embarks on a perilous journey into the shadows, performing illegal surgeries to reclaim her genius. Reunited with her mentor, Dr. Choi Deok-hee, who stripped her license, she navigates a dangerous game of revenge and power across Seoul’s underworld. Her quest for redemption and medical breakthroughs tests her morality amid high-stakes operations. Directed by Kim Jung-hyun, this 2025 Disney+ series, starring Park Eun-bin and Sul Kyung-gu, blends medical tension with a gripping odyssey of betrayal and resilience in a morally gray landscape.",
        releaseDate: "2025-03-19",
        director: "Kim Jung-hyun",
        genre: "Adventure",
        videoId: "K4mZ3vK9xQw",
      },
 
  ];